import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:ndu_project/openai/openai_config.dart';
import 'package:ndu_project/services/openai_service_secure.dart';
import 'package:ndu_project/services/voice_input_service.dart';
import 'package:ndu_project/services/docx_import_service.dart';
import 'package:ndu_project/utils/project_data_helper.dart';
import 'package:ndu_project/utils/rich_text_editing_controller.dart';
import 'package:ndu_project/utils/text_sanitizer.dart';
import 'package:ndu_project/widgets/open_editor_button.dart';
import 'package:ndu_project/widgets/text_formatting_toolbar.dart';

/// Debouncer utility to limit API calls while typing
class _Debouncer {
  _Debouncer({Duration? delay})
      : delay = delay ?? const Duration(milliseconds: 400);
  final Duration delay;
  Timer? _timer;
  void run(void Function() action) {
    _timer?.cancel();
    _timer = Timer(delay, action);
  }

  void dispose() => _timer?.cancel();
}

/// A text field with inline OpenAI-powered suggestions
/// - Shows suggestion chips beneath the field
/// - Suggestions are based on current text and prior project context
class AiSuggestingTextField extends StatefulWidget {
  const AiSuggestingTextField({
    super.key,
    required this.fieldLabel,
    required this.hintText,
    required this.sectionLabel,
    this.showLabel = true,
    this.enableAi = true,
    this.autoGenerate = false,
    this.autoGenerateSection,
    this.autoGenerateMaxTokens = 900,
    this.autoGenerateTemperature = 0.5,
    this.onAutoGenerated,
    this.onChanged,
    this.initialText,
    this.onRegenerate,
    this.onUndo,
    this.onRedo,
    this.canUndo = false,
    this.canRedo = false,
    this.enableDocxImport = true,
  });

  final String fieldLabel;
  final String hintText;
  final String sectionLabel;
  final bool showLabel;
  final bool enableAi;
  final bool autoGenerate;
  final String? autoGenerateSection;
  final int autoGenerateMaxTokens;
  final double autoGenerateTemperature;
  final ValueChanged<String>? onAutoGenerated;
  final ValueChanged<String>? onChanged;
  final String? initialText;
  final VoidCallback? onRegenerate;
  final VoidCallback? onUndo;
  final VoidCallback? onRedo;
  final bool canUndo;
  final bool canRedo;

  /// Whether to show the document-import button. Defaults to true.
  final bool enableDocxImport;

  @override
  State<AiSuggestingTextField> createState() => _AiSuggestingTextFieldState();
}

class _AiSuggestingTextFieldState extends State<AiSuggestingTextField> {
  static const int _basicPlanAiLimit = 2;
  final TextEditingController _controller = RichTextEditingController();
  final FocusNode _focusNode = FocusNode();
  final _debouncer = _Debouncer();
  List<String> _suggestions = const [];
  bool _loading = false;
  String? _error;
  bool _autoGenerated = false;
  bool _autoGenerating = false;
  bool _isReplaceMode = false;
  bool _showFormattingToolbar = false;
  bool _isListening = false;
  bool _voiceAvailable = true;
  bool _isImportingDoc = false;
  bool _isRewriting = false;
  final VoiceInputService _voiceService = VoiceInputService.instance;
  StreamSubscription<VoiceResult>? _voiceResultSub;
  StreamSubscription<VoiceStatus>? _voiceStatusSub;

  String get _aiUsageKey {
    final section = (widget.autoGenerateSection?.trim().isNotEmpty ?? false)
        ? widget.autoGenerateSection!.trim()
        : widget.sectionLabel.trim();
    return section.toLowerCase();
  }

  bool get _isBasicPlanProject {
    return ProjectDataHelper.getData(context).isBasicPlanProject;
  }

  int get _aiUsageCount {
    final data = ProjectDataHelper.getData(context);
    return data.aiUsageCounts[_aiUsageKey] ?? 0;
  }

  int get _remainingAiUses {
    if (!_isBasicPlanProject) return _basicPlanAiLimit;
    final remaining = _basicPlanAiLimit - _aiUsageCount;
    return remaining < 0 ? 0 : remaining;
  }

  bool get _isNotesField {
    final text = [
      widget.fieldLabel,
      widget.hintText,
      widget.sectionLabel,
      widget.autoGenerateSection ?? '',
    ].join(' ');
    return RegExp(r'\\bnotes?\\b', caseSensitive: false).hasMatch(text);
  }

  bool get _shouldForceAutoGenerate {
    final section = (widget.autoGenerateSection?.trim().isNotEmpty ?? false)
        ? widget.autoGenerateSection!.trim()
        : widget.sectionLabel.trim();
    final lower = section.toLowerCase();
    const execSignals = [
      'execution',
      'execution plan',
      'agile',
      'stakeholder alignment',
      'scope tracking',
      'risk tracking',
      'vendor tracking',
      'contract tracking',
      'punchlist',
      'operations maintenance',
      'ops maintenance',
      'closeout',
      'implementation',
      'mobilization',
      'go-live',
      'launch',
      'progress tracking',
      'team meetings',
      'staff team',
      'interface management',
    ];
    return execSignals.any(lower.contains);
  }

  bool get _autoGenerateEnabled =>
      widget.autoGenerate || _shouldForceAutoGenerate;

  bool get _aiEnabled =>
      widget.enableAi && (!_isNotesField || _shouldForceAutoGenerate);

  bool get _aiLimitReached => _isBasicPlanProject && _remainingAiUses <= 0;

  bool get _showLastChanceNote => _isBasicPlanProject && _remainingAiUses == 1;

  void _recordAiUsage() {
    if (!_isBasicPlanProject) return;
    final provider = ProjectDataHelper.getProvider(context);
    provider.updateField((data) {
      final counts = Map<String, int>.from(data.aiUsageCounts);
      final current = counts[_aiUsageKey] ?? 0;
      final next = current + 1;
      counts[_aiUsageKey] = next > _basicPlanAiLimit ? _basicPlanAiLimit : next;
      return data.copyWith(aiUsageCounts: counts);
    });
    setState(() {});
  }

  @override
  void initState() {
    super.initState();
    if ((widget.initialText ?? '').isNotEmpty) {
      _controller.text = TextSanitizer.sanitizeAiRichText(widget.initialText);
    }
    _controller.addListener(_onTextChanged);
    _focusNode.addListener(_handleFocusChanged);
    _initVoice();
    if (_aiEnabled && _autoGenerateEnabled) {
      WidgetsBinding.instance.addPostFrameCallback((_) => _maybeAutoGenerate());
    }
  }

  Future<void> _initVoice() async {
    final available = await _voiceService.initialize();
    if (mounted && available != _voiceAvailable) {
      setState(() => _voiceAvailable = available);
    }
  }

  /// Picks a .docx/.doc/.txt/.md/.csv/.rtf file and fills the field with its
  /// extracted plain-text content. Shows a loading spinner on the import
  /// icon during parsing and a success/error SnackBar afterwards.
  Future<void> _importDocument() async {
    if (_isImportingDoc) return;
    setState(() => _isImportingDoc = true);
    try {
      final outcome = await DocxImportService.pickAndExtract(context);
      if (!mounted) return;
      switch (outcome) {
        case DocxImportSuccess(:final result):
          _controller.text = TextSanitizer.sanitizeAiRichText(result.text);
          _controller.selection = TextSelection.fromPosition(
            TextPosition(offset: _controller.text.length),
          );
          widget.onChanged?.call(_controller.text);
          widget.onAutoGenerated?.call(_controller.text);
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(
                  'Imported ${result.wordCount} words from ${result.fileName}'),
              duration: const Duration(seconds: 3),
              behavior: SnackBarBehavior.floating,
            ),
          );
        case DocxImportError(:final reason, :final message):
          if (reason == DocxImportFailure.cancelledByUser) return;
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(message ?? 'Import failed: $reason'),
              duration: const Duration(seconds: 4),
              behavior: SnackBarBehavior.floating,
              backgroundColor: Colors.red.shade700,
            ),
          );
      }
    } finally {
      if (mounted) setState(() => _isImportingDoc = false);
    }
  }

  Future<void> _toggleVoiceInput() async {
    if (_isListening) {
      await _voiceService.stopListening();
      _cleanupVoiceSubs();
      if (mounted) setState(() => _isListening = false);
    } else {
      final started = await _voiceService.startListening(
        existingText: _controller.text,
      );
      if (!started) return;

      _voiceResultSub = _voiceService.onResult.listen((result) {
        if (!mounted) return;
        _controller.text = result.text;
        _controller.selection = TextSelection.fromPosition(
          TextPosition(offset: result.text.length),
        );
        widget.onChanged?.call(result.text);
        if (result.isFinal) {
          if (mounted) setState(() => _isListening = false);
          _cleanupVoiceSubs();
        }
      });

      _voiceStatusSub = _voiceService.onStatusChanged.listen((status) {
        if (status == VoiceStatus.stopped || status == VoiceStatus.error) {
          if (mounted) setState(() => _isListening = false);
          _cleanupVoiceSubs();
        }
      });

      if (mounted) setState(() => _isListening = true);
    }
  }

  void _cleanupVoiceSubs() {
    _voiceResultSub?.cancel();
    _voiceResultSub = null;
    _voiceStatusSub?.cancel();
    _voiceStatusSub = null;
  }

  @override
  void didUpdateWidget(covariant AiSuggestingTextField oldWidget) {
    super.didUpdateWidget(oldWidget);

    final sectionChanged =
        oldWidget.autoGenerateSection != widget.autoGenerateSection ||
            oldWidget.sectionLabel != widget.sectionLabel;
    final autoGenerateTurnedOn = !oldWidget.autoGenerate && widget.autoGenerate;

    if (sectionChanged || autoGenerateTurnedOn) {
      _autoGenerated = false;
    }

    final oldInitial = (oldWidget.initialText ?? '').trim();
    final newInitial = (widget.initialText ?? '').trim();
    if (oldInitial != newInitial &&
        _controller.text.trim().isEmpty &&
        newInitial.isNotEmpty) {
      _controller.text = TextSanitizer.sanitizeAiRichText(newInitial);
      _controller.selection = TextSelection.fromPosition(
        TextPosition(offset: _controller.text.length),
      );
    }

    if (_aiEnabled && _autoGenerateEnabled) {
      WidgetsBinding.instance.addPostFrameCallback((_) => _maybeAutoGenerate());
    }
  }

  @override
  void dispose() {
    _cleanupVoiceSubs();
    _controller.removeListener(_onTextChanged);
    _focusNode.removeListener(_handleFocusChanged);
    _controller.dispose();
    _focusNode.dispose();
    _debouncer.dispose();
    super.dispose();
  }

  void _handleFocusChanged() {
    if (!mounted) return;
    if (_focusNode.hasFocus) {
      if (!_showFormattingToolbar) {
        setState(() => _showFormattingToolbar = true);
      }
    } else if (_showFormattingToolbar) {
      setState(() => _showFormattingToolbar = false);
    }
  }

  void _onTextChanged() {
    widget.onChanged?.call(_controller.text);
    if (!_aiEnabled) return;
    _debouncer.run(() async {
      await _fetchSuggestions();
    });
  }

  Future<void> _maybeAutoGenerate() async {
    if (!_aiEnabled || !_autoGenerateEnabled) return;
    if (_autoGenerated || _autoGenerating) return;
    if (_controller.text.trim().isNotEmpty) return;
    if (_aiLimitReached) return;
    if (!OpenAiConfig.isConfigured) return;

    final section = widget.autoGenerateSection?.trim().isNotEmpty == true
        ? widget.autoGenerateSection!.trim()
        : widget.sectionLabel.trim();
    final data = ProjectDataHelper.getData(context);
    final sectionLower = section.toLowerCase();
    final useExecutiveContext = _shouldForceAutoGenerate ||
        sectionLower.contains('executive') ||
        sectionLower.contains('execution plan') ||
        sectionLower.contains('execution');
    final primaryContext = useExecutiveContext
        ? ProjectDataHelper.buildExecutivePlanContext(data,
            sectionLabel: section)
        : ProjectDataHelper.buildFepContext(data, sectionLabel: section);
    final contextText = primaryContext.trim().isEmpty
        ? ProjectDataHelper.buildProjectContextScan(data, sectionLabel: section)
        : primaryContext;
    if (contextText.trim().isEmpty) return;

    if (mounted) {
      setState(() {
        _autoGenerating = true;
        _error = null;
      });
    } else {
      _autoGenerating = true;
    }

    var generatedSuccessfully = false;
    try {
      final ai = OpenAiServiceSecure();
      final text = await ai.generateFepSectionText(
        section: section,
        context: contextText,
        maxTokens: widget.autoGenerateMaxTokens,
        temperature: widget.autoGenerateTemperature,
      );
      if (!mounted) return;
      _recordAiUsage();
      if (_controller.text.trim().isEmpty && text.trim().isNotEmpty) {
        _controller.text = TextSanitizer.sanitizeAiRichText(text);
        _controller.selection = TextSelection.fromPosition(
          TextPosition(offset: _controller.text.length),
        );
        widget.onChanged?.call(_controller.text);
        widget.onAutoGenerated?.call(_controller.text);
        generatedSuccessfully = true;
      }
    } catch (e) {
      if (!mounted) return;
      setState(() {
        final warning = OpenAiConfig.configurationWarning();
        _error = warning ??
            'Unable to auto-generate right now. You can continue typing or use AI suggest.';
      });
    } finally {
      if (!mounted) {
        _autoGenerating = false;
      } else {
        setState(() {
          _autoGenerating = false;
          if (generatedSuccessfully) {
            _autoGenerated = true;
          }
        });
      }
    }
  }

  Future<void> _fetchSuggestions() async {
    if (!_aiEnabled) return;
    final text = _controller.text.trim();
    if (_aiLimitReached) {
      setState(() {
        _suggestions = const [];
        _error = null;
      });
      return;
    }

    final data = ProjectDataHelper.getData(context);
    final contextSection =
        (widget.autoGenerateSection?.trim().isNotEmpty ?? false)
            ? widget.autoGenerateSection!.trim()
            : widget.sectionLabel.trim();
    final sectionLower = contextSection.toLowerCase();
    final useExecutiveContext = _shouldForceAutoGenerate ||
        sectionLower.contains('executive') ||
        sectionLower.contains('execution plan') ||
        sectionLower.contains('execution');
    final primaryContext = useExecutiveContext
        ? ProjectDataHelper.buildExecutivePlanContext(data,
            sectionLabel: contextSection)
        : ProjectDataHelper.buildFepContext(data, sectionLabel: contextSection);
    final contextText = primaryContext.trim().isEmpty
        ? ProjectDataHelper.buildProjectContextScan(data,
            sectionLabel: contextSection)
        : primaryContext;
    final seedText = text.isNotEmpty
        ? text
        : (widget.hintText.trim().isNotEmpty
            ? widget.hintText.trim()
            : widget.fieldLabel.trim());
    if (seedText.isEmpty) {
      setState(() {
        _suggestions = const [];
        _error = null;
      });
      return;
    }

    setState(() {
      _loading = true;
      _error = null;
    });

    try {
      final items = await OpenAiAutocompleteService.instance.fetchSuggestions(
        fieldName: widget.fieldLabel,
        currentText: seedText,
        context: contextText,
        maxSuggestions: 4,
      );
      if (!mounted) return;
      setState(() {
        _suggestions =
            items.map((s) => TextSanitizer.sanitizeAiRichText(s)).toList();
        _loading = false;
      });
      _recordAiUsage();
    } catch (e) {
      if (!mounted) return;
      setState(() {
        // Check if OpenAI is configured
        if (!OpenAiConfig.isConfigured) {
          _error = 'AI service is starting up. Please try again in a moment.';
        } else {
          final warn = OpenAiConfig.configurationWarning();
          _error = warn ?? e.toString();
        }
        _loading = false;
      });
    }
  }

  void _applySuggestion(String suggestion) {
    final sanitized = TextSanitizer.sanitizeAiRichText(suggestion);

    if (_isReplaceMode) {
      // Replace entire field content
      _controller.text = sanitized;
      _controller.selection = TextSelection.fromPosition(
          TextPosition(offset: _controller.text.length));
    } else {
      // Insert at cursor position
      final current = _controller.text;
      final selection = _controller.selection;
      final beforeCursor = current.substring(0, selection.baseOffset);
      final afterCursor = current.substring(selection.extentOffset);
      final needsSpace = beforeCursor.isNotEmpty &&
          !beforeCursor.endsWith('\n') &&
          !beforeCursor.endsWith(' ') &&
          !beforeCursor.endsWith('.');
      final next =
          beforeCursor + (needsSpace ? ' ' : '') + sanitized + afterCursor;
      _controller.text = next;
      final newOffset =
          selection.baseOffset + (needsSpace ? 1 : 0) + sanitized.length;
      _controller.selection =
          TextSelection.fromPosition(TextPosition(offset: newOffset));
    }
    widget.onChanged?.call(_controller.text);
  }

  /// Rewrite / correct the existing text in the field. The AI receives the
  /// current text plus project context and returns a polished version that
  /// fixes grammar, tightens wording, and ensures professional tone. The
  /// user sees the rewritten text replace the field content (with the
  /// original preserved in the undo stack).
  Future<void> _rewriteText() async {
    if (_isRewriting) return;
    final currentText = _controller.text.trim();
    if (currentText.isEmpty) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content:
              Text('Type some text first, then tap AI Rewrite to polish it.'),
          duration: Duration(seconds: 3),
        ),
      );
      return;
    }
    if (!OpenAiConfig.isConfigured) {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(OpenAiConfig.configurationWarning() ??
              'AI service is not configured yet.'),
          duration: const Duration(seconds: 3),
        ),
      );
      return;
    }

    setState(() {
      _isRewriting = true;
      _error = null;
    });

    try {
      final data = ProjectDataHelper.getData(context);
      final contextSection =
          (widget.autoGenerateSection?.trim().isNotEmpty ?? false)
              ? widget.autoGenerateSection!.trim()
              : widget.sectionLabel.trim();
      final projectContext =
          ProjectDataHelper.buildFepContext(data, sectionLabel: contextSection);
      final ai = OpenAiServiceSecure();
      final rewritten = await ai.rewriteExistingText(
        section: contextSection,
        currentText: currentText,
        projectContext: projectContext,
      );
      if (!mounted) return;
      final sanitized = TextSanitizer.sanitizeAiRichText(rewritten);
      if (sanitized.trim().isNotEmpty && sanitized.trim() != currentText) {
        _controller.text = sanitized;
        _controller.selection = TextSelection.fromPosition(
          TextPosition(offset: _controller.text.length),
        );
        widget.onChanged?.call(_controller.text);
        widget.onAutoGenerated?.call(_controller.text);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('AI rewrote and polished the text.'),
            duration: Duration(seconds: 2),
            backgroundColor: Color(0xFF10B981),
          ),
        );
      } else if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('AI could not improve the text further.'),
            duration: Duration(seconds: 2),
          ),
        );
      }
    } catch (e) {
      if (!mounted) return;
      setState(() {
        _error = OpenAiConfig.configurationWarning() ?? e.toString();
      });
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('AI rewrite failed: $_error'),
          duration: const Duration(seconds: 3),
          backgroundColor: const Color(0xFFDC2626),
        ),
      );
    } finally {
      if (mounted) {
        setState(() => _isRewriting = false);
      }
    }
  }

  // ignore: unused_element
  Future<void> _copyToClipboard(String suggestion) async {
    await Clipboard.setData(ClipboardData(text: suggestion));

    // Auto-paste into active field
    _applySuggestion(suggestion);

    if (mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Copied and pasted to field'),
          duration: Duration(seconds: 2),
        ),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_aiEnabled &&
        _autoGenerateEnabled &&
        !_autoGenerated &&
        !_autoGenerating &&
        _controller.text.trim().isEmpty &&
        !_aiLimitReached) {
      // Listen to project data updates so auto-generation can retry once context
      // becomes available after upstream pages are completed.
      ProjectDataHelper.getDataListening(context);
      WidgetsBinding.instance.addPostFrameCallback((_) => _maybeAutoGenerate());
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        if (widget.showLabel) ...[
          Text(
            widget.fieldLabel,
            style: const TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.w600,
              color: Color(0xFF111827),
            ),
          ),
          const SizedBox(height: 14),
        ],
        Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (_showFormattingToolbar)
              Expanded(
                child: TextFormattingToolbar(controller: _controller),
              )
            else
              const Spacer(),
            IconButton(
              tooltip: _showFormattingToolbar
                  ? 'Hide formatting toolbar'
                  : 'Show formatting toolbar',
              icon: Icon(
                _showFormattingToolbar
                    ? Icons.edit_off_outlined
                    : Icons.edit_note_outlined,
                size: 20,
                color: const Color(0xFF6B7280),
              ),
              onPressed: () {
                setState(
                    () => _showFormattingToolbar = !_showFormattingToolbar);
                if (_showFormattingToolbar) {
                  _focusNode.requestFocus();
                }
              },
            ),
            const SizedBox(width: 8),
            OpenEditorButton(
              actions: _buildEditorActions(),
              isLoading: _isListening ||
                  _loading ||
                  _isRewriting ||
                  _isImportingDoc ||
                  _autoGenerating,
            ),
          ],
        ),
        const SizedBox(height: 8),
        Stack(
          children: [
            TextField(
              controller: _controller,
              focusNode: _focusNode,
              onTap: () {
                if (!_showFormattingToolbar) {
                  setState(() => _showFormattingToolbar = true);
                }
              },
              maxLines: 12,
              minLines: 8,
              decoration: InputDecoration(
                hintText: widget.hintText,
                hintStyle:
                    const TextStyle(color: Color(0xFF9CA3AF), fontSize: 14),
                contentPadding:
                    const EdgeInsets.symmetric(horizontal: 20, vertical: 20),
                filled: true,
                fillColor: Colors.white,
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(16),
                  borderSide: BorderSide(color: Color(0xFFE5E7EB)),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(16),
                  borderSide:
                      BorderSide(color: Color(0xFFFFD700), width: 1.6),
                ),
                suffixIcon: null,
              ),
              style: const TextStyle(
                  fontSize: 14, color: Color(0xFF111827), height: 1.5),
            ),
          ],
        ),
        if (_aiEnabled && _autoGenerating && !_autoGenerated) ...[
          const SizedBox(height: 8),
          Row(
            children: [
              const SizedBox(
                  width: 16,
                  height: 16,
                  child: CircularProgressIndicator(strokeWidth: 2)),
              const SizedBox(width: 8),
              Text(
                'AI is generating content...',
                style: TextStyle(
                    fontSize: 12,
                    color: Colors.grey[600],
                    fontStyle: FontStyle.italic),
              ),
            ],
          ),
        ],
        if (_aiEnabled && _isBasicPlanProject && _aiLimitReached) ...[
          const SizedBox(height: 10),
          _AiLimitBanner(
            message:
                'AI suggestions are not available for this section on the Basic plan.',
            background: const Color(0xFFF3F4F6),
            border: const Color(0xFFE5E7EB),
            textColor: const Color(0xFF6B7280),
          ),
        ] else if (_aiEnabled && _showLastChanceNote) ...[
          const SizedBox(height: 10),
          const _AiLimitBanner(
            message: 'AI KAZ is available to assist one last time.',
            background: Color(0xFFFFF7ED),
            border: Color(0xFFFCD34D),
            textColor: Color(0xFF92400E),
          ),
        ],
        const SizedBox(height: 10),
        if ((_error ?? '').isNotEmpty)
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
            margin: const EdgeInsets.only(bottom: 8),
            decoration: BoxDecoration(
              color: Color(0xFFFEF2F2),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: Color(0xFFFCA5A5)),
            ),
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                const Icon(Icons.warning_amber_rounded,
                    size: 18, color: Color(0xFFB91C1C)),
                const SizedBox(width: 10),
                Expanded(
                  child: Text(
                    _error!,
                    style: const TextStyle(
                        fontSize: 13, color: Color(0xFFB91C1C), height: 1.4),
                  ),
                ),
              ],
            ),
          ),
        if (_aiEnabled && _suggestions.isNotEmpty) ...[
          Row(
            children: [
              const Text(
                'Mode:',
                style: TextStyle(fontSize: 12, color: Color(0xFF6B7280)),
              ),
              const SizedBox(width: 8),
              Switch(
                value: _isReplaceMode,
                onChanged: (value) => setState(() => _isReplaceMode = value),
                materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
              ),
              const SizedBox(width: 4),
              Text(
                _isReplaceMode ? 'Replace All' : 'Insert at Cursor',
                style: const TextStyle(fontSize: 12, color: Color(0xFF6B7280)),
              ),
            ],
          ),
          const SizedBox(height: 8),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: _suggestions
                .map((s) => ActionChip(
                      backgroundColor: const Color(0xFFE1EEFF),
                      shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(999)),
                      label: Text(
                        s,
                        style: const TextStyle(
                            fontSize: 12,
                            fontWeight: FontWeight.w600,
                            color: Color(0xFF1F2937)),
                      ),
                      avatar: const Icon(Icons.add_rounded,
                          size: 16, color: Color(0xFF1F2937)),
                      onPressed: () => _applySuggestion(s),
                    ))
                .toList(),
          ),
        ],
      ],
    );
  }

  /// Builds the list of [EditorAction]s surfaced in the Open Editor popup.
  ///
  /// Actions are gated by the same flags that previously gated each inline
  /// suffix icon — so the popup only shows items that are actually
  /// applicable to the current field state (e.g. undo/redo only appear
  /// when callbacks are wired up and the corresponding stack has entries).
  List<EditorAction> _buildEditorActions() {
    final aiAvailable = _aiEnabled && !_aiLimitReached;
    final docxAvailable = widget.enableDocxImport;
    final voiceAvailable = widget.enableAi;

    return <EditorAction>[
      if (aiAvailable)
        EditorAction(
          id: 'ai_suggest',
          icon: Icons.auto_awesome,
          label: 'AI suggest',
          tooltip: 'Generate suggestions based on project context',
          accent: const Color(0xFFF59E0B),
          onTap: _fetchSuggestions,
        ),
      if (aiAvailable)
        EditorAction(
          id: 'ai_rewrite',
          icon: Icons.spellcheck_outlined,
          label: 'AI rewrite / correct',
          tooltip: 'Polish text you have already typed',
          accent: const Color(0xFF10B981),
          onTap: _rewriteText,
        ),
      if (docxAvailable)
        EditorAction(
          id: 'docx',
          icon: Icons.upload_file,
          label: 'Import from .docx / .doc',
          tooltip: 'Extract text from a Word document',
          accent: const Color(0xFF0EA5E9),
          onTap: _isImportingDoc ? () {} : _importDocument,
          enabled: !_isImportingDoc,
        ),
      if (voiceAvailable)
        EditorAction(
          id: 'voice',
          icon: _isListening ? Icons.mic : Icons.mic_none_outlined,
          label: _isListening ? 'Stop voice input' : 'Voice input',
          tooltip: 'Tap to speak — your words will be transcribed',
          accent: const Color(0xFFFFB800),
          onTap: _toggleVoiceInput,
        ),
      if (widget.onRegenerate != null)
        EditorAction(
          id: 'regenerate',
          icon: Icons.refresh,
          label: 'Regenerate this field',
          tooltip: 'Re-run the original AI generation for this field',
          accent: const Color(0xFF2563EB),
          onTap: widget.onRegenerate!,
        ),
      if (widget.onUndo != null && widget.canUndo)
        EditorAction(
          id: 'undo',
          icon: Icons.undo,
          label: 'Undo last change',
          tooltip: 'Revert the most recent edit',
          accent: const Color(0xFF6B7280),
          onTap: widget.onUndo!,
        ),
      if (widget.onRedo != null && widget.canRedo)
        EditorAction(
          id: 'redo',
          icon: Icons.redo,
          label: 'Redo last change',
          tooltip: 'Re-apply the most recently undone edit',
          accent: const Color(0xFF6B7280),
          onTap: widget.onRedo!,
        ),
      if (_controller.text.isNotEmpty)
        EditorAction(
          id: 'clear',
          icon: Icons.delete_sweep,
          label: 'Clear all content',
          tooltip: 'Remove everything in this field',
          accent: const Color(0xFFEF4444),
          isDestructive: true,
          onTap: () {
            _controller.clear();
            setState(() {});
          },
        ),
    ];
  }
}

class _AiLimitBanner extends StatelessWidget {
  const _AiLimitBanner({
    super.key,
    required this.message,
    required this.background,
    required this.border,
    required this.textColor,
  });

  final String message;
  final Color background;
  final Color border;
  final Color textColor;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 12),
      margin: const EdgeInsets.only(bottom: 8),
      decoration: BoxDecoration(
        color: background,
        borderRadius: BorderRadius.circular(10),
        border: Border.all(color: border),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Icon(Icons.info_outline, size: 18, color: textColor),
          const SizedBox(width: 10),
          Expanded(
            child: Text(
              message,
              style: TextStyle(fontSize: 13, color: textColor, height: 1.4),
            ),
          ),
        ],
      ),
    );
  }
}
