import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'package:ndu_project/models/project_data_model.dart';
import 'package:ndu_project/providers/project_data_provider.dart';
import 'package:ndu_project/screens/launch_checklist_screen.dart';
import 'package:ndu_project/screens/scope_completion_screen.dart';
import 'package:ndu_project/widgets/kaz_ai_chat_bubble.dart';
import 'package:ndu_project/widgets/launch_phase_navigation.dart';
import 'package:ndu_project/widgets/planning_phase_header.dart';

import 'package:ndu_project/widgets/voice_text_field.dart';
import 'package:ndu_project/utils/pdf_export_helper.dart';
import 'package:ndu_project/utils/project_data_helper.dart';
class RiskTrackingWorkspaceScreen extends StatefulWidget {
 const RiskTrackingWorkspaceScreen({super.key});

 static void open(BuildContext context) {
 Navigator.of(context).push(
 MaterialPageRoute(builder: (_) => const RiskTrackingWorkspaceScreen()),
 );
 }

 @override
 State<RiskTrackingWorkspaceScreen> createState() =>
 _RiskTrackingWorkspaceScreenState();
}

class _RiskTrackingWorkspaceScreenState
 extends State<RiskTrackingWorkspaceScreen> {
 final Set<String> _selectedFilters = {'All risks'};
 final List<_RiskData> _risks = [];
 final List<_SignalData> _signals = [];
 final List<_MitigationData> _mitigations = [];
 bool _isGenerating = false;
 bool _autoGenerated = false;
 Timer? _saveDebounce;

 String? get _projectId {
 try {
 return ProjectDataInherited.maybeOf(context)?.projectData.projectId;
 } catch (e) {
 return null;
 }
 }

 String? get _userId {
 try {
 return FirebaseAuth.instance.currentUser?.uid;
 } catch (e) {
 return null;
 }
 }

 @override
 void initState() {
 super.initState();
 _loadData();
 }

 @override
 void dispose() {
 _saveDebounce?.cancel();
 super.dispose();
 }

 Future<void> _loadData() async {
 final sharedProjectData =
 ProjectDataInherited.maybeRead(context)?.projectData;
 if (sharedProjectData != null &&
 (sharedProjectData.executionRiskItems.isNotEmpty ||
 sharedProjectData.executionRiskSignals.isNotEmpty ||
 sharedProjectData.executionRiskMitigations.isNotEmpty)) {
 setState(() {
 _risks
 ..clear()
 ..addAll(
 sharedProjectData.executionRiskItems.map(_RiskData.fromShared));
 _signals
 ..clear()
 ..addAll(sharedProjectData.executionRiskSignals
 .map(_SignalData.fromShared));
 _mitigations
 ..clear()
 ..addAll(sharedProjectData.executionRiskMitigations
 .map(_MitigationData.fromShared));
 });
 await _autoGenerateIfNeeded();
 return;
 }

 final projectId = _projectId;
 if (projectId == null || projectId.isEmpty) {
 return;
 }

 try {
 final doc = await FirebaseFirestore.instance
 .collection('projects')
 .doc(projectId)
 .collection('execution_phase_sections')
 .doc('risk_tracking')
 .get();

 if (!mounted) return;

 final data = doc.data();
 if (data != null) {
 setState(() {
 _risks.clear();
 _risks.addAll(((data['riskItems'] as List?) ?? const []).map(
 (item) => _RiskData.fromMap(Map<String, dynamic>.from(item))));

 _signals.clear();
 _signals.addAll(((data['riskSignals'] as List?) ?? const []).map(
 (item) => _SignalData.fromMap(Map<String, dynamic>.from(item))));

 _mitigations.clear();
 _mitigations.addAll(((data['mitigationPlans'] as List?) ?? const [])
 .map((item) =>
 _MitigationData.fromMap(Map<String, dynamic>.from(item))));
 });
 _syncSharedProjectData();
 await ProjectDataInherited.maybeRead(context)
 ?.saveToFirebase(checkpoint: 'risk_tracking');
 }

 await _autoGenerateIfNeeded();
 } catch (e) {
 debugPrint('Error loading risk tracking: $e');
 }
 }

 Future<void> _autoGenerateIfNeeded() async {
 if (_autoGenerated || _isGenerating) return;
 if (_risks.isNotEmpty || _signals.isNotEmpty || _mitigations.isNotEmpty) {
 return;
 }

 _autoGenerated = true;
 await _generateAiDrafts(replaceExisting: true);
 }

 Future<void> _generateAiDrafts({bool replaceExisting = false}) async {
 if (_isGenerating) return;
 setState(() => _isGenerating = true);

 try {
 await Future.delayed(const Duration(seconds: 1));

 if (!mounted) return;

 if (replaceExisting) {
 _risks.clear();
 _signals.clear();
 _mitigations.clear();
 }

 final now = DateTime.now();
 setState(() {
 if (_risks.isEmpty) {
 _risks.addAll([
 _RiskData(
 id: DateTime.now().microsecondsSinceEpoch.toString(),
 title: 'Scope creep risk',
 description:
 'Potential for project scope to expand beyond original boundaries without proper controls',
 category: 'Project Management',
 owner: 'Project Manager',
 likelihoodScore: 3,
 impactScore: 4,
 probability: 'Medium',
 impact: 'High',
 riskScore: 12,
 status: 'Open',
 triggerEvents:
 'New feature requests from stakeholders, unclear requirements',
 mitigationStrategy: 'Implement formal change control process',
 nextReview: _formatDate(now.add(const Duration(days: 7))),
 associatedMitigation: 'Scope freeze implementation',
 createdAt: _formatDate(now),
 lastModified: _formatDate(now),
 ),
 _RiskData(
 id: (DateTime.now().microsecondsSinceEpoch + 1).toString(),
 title: 'Resource availability',
 description:
 'Key team members may be unavailable during critical project phases',
 category: 'Resource',
 owner: 'Resource Manager',
 likelihoodScore: 2,
 impactScore: 3,
 probability: 'Low',
 impact: 'Medium',
 riskScore: 6,
 status: 'Monitoring',
 triggerEvents: 'Team member leaves, competing priorities emerge',
 mitigationStrategy:
 'Cross-train team members, maintain contingency buffer',
 nextReview: _formatDate(now.add(const Duration(days: 14))),
 associatedMitigation: 'Contingency resource plan',
 createdAt: _formatDate(now),
 lastModified: _formatDate(now),
 ),
 _RiskData(
 id: (DateTime.now().microsecondsSinceEpoch + 2).toString(),
 title: 'Technical dependency',
 description:
 'Project depends on external API that may have stability issues',
 category: 'Technical',
 owner: 'Tech Lead',
 likelihoodScore: 4,
 impactScore: 5,
 probability: 'High',
 impact: 'Critical',
 riskScore: 20,
 status: 'At Risk',
 triggerEvents: 'API downtime, breaking changes, rate limiting',
 mitigationStrategy:
 'Implement fallback mechanisms, SLA monitoring',
 nextReview: _formatDate(now.add(const Duration(days: 3))),
 associatedMitigation: 'API fallback implementation',
 createdAt: _formatDate(now),
 lastModified: _formatDate(now),
 ),
 ]);
 }

 if (_signals.isEmpty) {
 _signals.addAll([
 _SignalData(
 id: DateTime.now().microsecondsSinceEpoch.toString(),
 title: 'Vendor delay warning',
 detail:
 'Key vendor indicating potential 2-week delay due to supply chain issues',
 severity: 'High',
 source: 'Vendor Communication',
 dateDetected: _formatDate(now),
 confidenceLevel: 'High',
 associatedRiskId: _risks.isNotEmpty ? _risks[0].id : '',
 ),
 _SignalData(
 id: (DateTime.now().microsecondsSinceEpoch + 1).toString(),
 title: 'Team capacity concerns',
 detail:
 'Engineering team running at 95% capacity, risk of burnout',
 severity: 'Medium',
 source: 'Team Standup',
 dateDetected: _formatDate(now.subtract(const Duration(days: 2))),
 confidenceLevel: 'Medium',
 associatedRiskId: _risks.length > 1 ? _risks[1].id : '',
 ),
 _SignalData(
 id: (DateTime.now().microsecondsSinceEpoch + 2).toString(),
 title: 'API instability detected',
 detail:
 'Third-party API showing increased latency and occasional timeouts',
 severity: 'Critical',
 source: 'Monitoring Dashboard',
 dateDetected: _formatDate(now),
 confidenceLevel: 'High',
 associatedRiskId: _risks.length > 2 ? _risks[2].id : '',
 ),
 ]);
 }

 if (_mitigations.isEmpty) {
 _mitigations.addAll([
 _MitigationData(
 id: DateTime.now().microsecondsSinceEpoch.toString(),
 title: 'Scope freeze implementation',
 description:
 'Implement formal change control process with stakeholder approval gates',
 owner: 'Project Manager',
 status: 'In Progress',
 dueDate: _formatDate(now.add(const Duration(days: 10))),
 progress: 65,
 estimatedCost: '5000',
 associatedRiskId: _risks.isNotEmpty ? _risks[0].id : '',
 statusNotes:
 'Stakeholder alignment achieved, documentation in progress',
 createdAt: _formatDate(now),
 ),
 _MitigationData(
 id: (DateTime.now().microsecondsSinceEpoch + 1).toString(),
 title: 'Contingency resource plan',
 description:
 'Identify and onboard backup resources for critical roles',
 owner: 'Resource Manager',
 status: 'Planning',
 dueDate: _formatDate(now.add(const Duration(days: 14))),
 progress: 30,
 estimatedCost: '15000',
 associatedRiskId: _risks.length > 1 ? _risks[1].id : '',
 statusNotes: 'Vendor evaluation in progress',
 createdAt: _formatDate(now),
 ),
 _MitigationData(
 id: (DateTime.now().microsecondsSinceEpoch + 2).toString(),
 title: 'API fallback implementation',
 description:
 'Build resilient architecture with fallback mechanisms',
 owner: 'Tech Lead',
 status: 'In Progress',
 dueDate: _formatDate(now.add(const Duration(days: 5))),
 progress: 80,
 estimatedCost: '8000',
 associatedRiskId: _risks.length > 2 ? _risks[2].id : '',
 statusNotes: 'Circuit breaker pattern implemented, testing phase',
 createdAt: _formatDate(now),
 ),
 ]);
 }
 });

 _saveToFirestore();
 } catch (e) {
 debugPrint('AI generation failed: $e');
 } finally {
 if (mounted) setState(() => _isGenerating = false);
 }
 }

 String _formatDate(DateTime date) {
 return '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
 }

 void _syncSharedProjectData() {
 final provider = ProjectDataInherited.maybeRead(context);
 if (provider == null) return;
 final riskTitlesById = {
 for (final risk in _risks)
 if (risk.id.trim().isNotEmpty) risk.id.trim(): risk.title.trim(),
 };
 provider.updateField(
 (data) => data.copyWith(
 executionRiskItems:
 _risks.map((risk) => risk.toShared()).toList(growable: false),
 executionRiskSignals:
 _signals.map((signal) => signal.toShared()).toList(growable: false),
 executionRiskMitigations: _mitigations
 .map((mitigation) => mitigation.toShared(
 associatedRiskTitle:
 riskTitlesById[mitigation.associatedRiskId.trim()] ?? '',
 ))
 .toList(growable: false),
 ),
 );
 }

 void _saveToFirestore() {
 _syncSharedProjectData();
 final projectId = _projectId;
 if (projectId == null || projectId.isEmpty) return;

 _saveDebounce?.cancel();
 _saveDebounce = Timer(const Duration(milliseconds: 600), () async {
 try {
 final provider = ProjectDataInherited.maybeRead(context);
 await provider?.saveToFirebase(checkpoint: 'risk_tracking');
 await FirebaseFirestore.instance
 .collection('projects')
 .doc(projectId)
 .collection('execution_phase_sections')
 .doc('risk_tracking')
 .set({
 'riskItems': _risks.map((r) => r.toMap()).toList(),
 'riskSignals': _signals.map((s) => s.toMap()).toList(),
 'mitigationPlans': _mitigations.map((m) => m.toMap()).toList(),
 'updatedAt': FieldValue.serverTimestamp(),
 'updatedBy': _userId,
 }, SetOptions(merge: true));
 } catch (e) {
 debugPrint('Error saving risk tracking: $e');
 }
 });
 }

 List<_RiskData> get _filteredRisks {
 if (_selectedFilters.contains('All risks')) return _risks;
 return _risks.where((risk) {
 if (_selectedFilters.contains('High impact')) {
 return risk.impact == 'High' || risk.impact == 'Critical';
 }
 if (_selectedFilters.contains('Needs review')) {
 return risk.status == 'Open' || risk.status == 'At Risk';
 }
 if (_selectedFilters.contains('Blocked')) return risk.status == 'Blocked';
 if (_selectedFilters.contains('Critical risks')) {
 return risk.riskScore >= 15;
 }
 return true;
 }).toList();
 }

 @override
 Widget build(BuildContext context) {
 final isMobile = MediaQuery.sizeOf(context).width < 900;

 return Scaffold(
 backgroundColor: Colors.white,
 body: SafeArea(
 child: Stack(
 children: [
 SingleChildScrollView(
 padding: const EdgeInsets.all(24),
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 PlanningPhaseHeader(
 title: 'Risk Tracking Workspace',
showNavigationButtons: false, onExportPdf: _exportPdf),
 const SizedBox(height: 16),
 _buildHeader(),
 const SizedBox(height: 24),
 _buildFilterChips(),
 const SizedBox(height: 24),
 _buildMetricsGrid(),
 const SizedBox(height: 32),
 _buildRiskRegister(isMobile),
 const SizedBox(height: 32),
 if (isMobile) ...[
 _buildRiskSignals(),
 const SizedBox(height: 32),
 _buildMitigationPlans(),
 ] else
 Row(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Expanded(child: _buildRiskSignals()),
 const SizedBox(width: 24),
 Expanded(child: _buildMitigationPlans()),
 ],
 ),
 const SizedBox(height: 24),
 LaunchPhaseNavigation(
 backLabel: 'Back: Launch Checklist',
 nextLabel: 'Next: Scope Completion',
 onBack: () => LaunchChecklistScreen.open(context),
 onNext: () => ScopeCompletionScreen.open(context),
 ),
 const SizedBox(height: 48),
 ],
 ),
 ),
 const KazAiChatBubble(),
 ],
 ),
 ),
 );
 }

 Widget _buildHeader() {
 return Row(
 children: [
 IconButton(
 icon: const Icon(Icons.arrow_back_ios_new, size: 20),
 onPressed: () => Navigator.of(context).pop(),
 style: IconButton.styleFrom(
 backgroundColor: Colors.white,
 foregroundColor: const Color(0xFF111827),
 padding: const EdgeInsets.all(12),
 ),
 ),
 const SizedBox(width: 16),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Row(
 children: [
 Container(
 padding: const EdgeInsets.symmetric(
 horizontal: 10,
 vertical: 4,
 ),
 decoration: BoxDecoration(
 color: const Color(0xFFFEE2E2),
 borderRadius: BorderRadius.circular(6),
 ),
 child: const Text(
 'RISK MANAGEMENT',
 style: TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w700,
 color: Color(0xFFDC2626),
 letterSpacing: 1,
 ),
 ),
 ),
 const SizedBox(width: 12),
 const Text(
 'Risk Tracking Workspace',
 style: TextStyle(
 fontSize: 24,
 fontWeight: FontWeight.w800,
 color: Color(0xFF111827),
 ),
 ),
 ],
 ),
 const SizedBox(height: 4),
 const Text(
 'Monitor, assess, and mitigate project risks proactively',
 style: TextStyle(
 fontSize: 14,
 color: Color(0xFF6B7280),
 fontWeight: FontWeight.w500,
 ),
 ),
 ],
 ),
 ),
 const SizedBox(width: 16),
 Row(
 children: [
 _buildActionButton(
 icon: Icons.auto_awesome_outlined,
 label: 'AI Draft',
 isLoading: _isGenerating,
 onTap: _generateAiDrafts,
 color: const Color(0xFF8B5CF6),
 ),
 const SizedBox(width: 12),
 _buildActionButton(
 icon: Icons.add,
 label: 'Add Risk',
 onTap: _showRiskEditor,
 color: const Color(0xFF6366F1),
 ),
 ],
 ),
 ],
 );
 }

 Widget _buildActionButton({
 required IconData icon,
 required String label,
 required VoidCallback onTap,
 required Color color,
 bool isLoading = false,
 }) {
 return Material(
 color: color,
 borderRadius: BorderRadius.circular(12),
 child: InkWell(
 onTap: isLoading ? null : onTap,
 borderRadius: BorderRadius.circular(12),
 child: Container(
 padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
 child: Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 if (isLoading)
 const SizedBox(
 width: 16,
 height: 16,
 child: CircularProgressIndicator(
 strokeWidth: 2,
 valueColor: AlwaysStoppedAnimation<Color>(Colors.white),
 ),
 )
 else
 Icon(icon, size: 18, color: Colors.white),
 const SizedBox(width: 8),
 Text(
 label,
 style: const TextStyle(
 fontSize: 14,
 fontWeight: FontWeight.w600,
 color: Colors.white,
 ),
 ),
 ],
 ),
 ),
 ),
 );
 }

 Widget _buildFilterChips() {
 return Wrap(
 spacing: 10,
 runSpacing: 10,
 children: [
 'All risks',
 'High impact',
 'Needs review',
 'Blocked',
 'Critical risks',
 ]
 .map((filter) => FilterChip(
 label: Text(filter),
 labelStyle: TextStyle(
 fontSize: 13,
 fontWeight: FontWeight.w600,
 color: _selectedFilters.contains(filter)
 ? Colors.white
 : const Color(0xFF4B5563),
 ),
 selected: _selectedFilters.contains(filter),
 onSelected: (_) {
 setState(() {
 _selectedFilters
 ..clear()
 ..add(filter);
 });
 },
 selectedColor: const Color(0xFF6366F1),
 backgroundColor: Colors.white,
 checkmarkColor: Colors.white,
 shape: RoundedRectangleBorder(
 borderRadius: BorderRadius.circular(8),
 side: BorderSide(
 color: _selectedFilters.contains(filter)
 ? const Color(0xFF6366F1)
 : const Color(0xFFE5E7EB),
 ),
 ),
 padding:
 const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
 ))
 .toList(),
 );
 }

 Widget _buildMetricsGrid() {
 final highImpactCount = _risks
 .where((r) => r.impact == 'High' || r.impact == 'Critical')
 .length;
 final criticalRisksCount = _risks.where((r) => r.riskScore >= 15).length;
 final avgRiskScore = _risks.isEmpty
 ? 0
 : (_risks.map((r) => r.riskScore).reduce((a, b) => a + b) /
 _risks.length)
 .round();

 return Row(
 children: [
 Expanded(
 child: _buildMetricCard(
 icon: Icons.warning_amber_rounded,
 iconColor: const Color(0xFFEF4444),
 iconBg: const Color(0xFFFEE2E2),
 label: 'Active Risks',
 value: _risks.length.toString(),
 ),
 ),
 const SizedBox(width: 16),
 Expanded(
 child: _buildMetricCard(
 icon: Icons.priority_high_rounded,
 iconColor: const Color(0xFFF97316),
 iconBg: const Color(0xFFFFEDD5),
 label: 'High Impact',
 value: highImpactCount.toString(),
 ),
 ),
 const SizedBox(width: 16),
 Expanded(
 child: _buildMetricCard(
 icon: Icons.analytics_rounded,
 iconColor: const Color(0xFFDC2626),
 iconBg: const Color(0xFFFEE2E2),
 label: 'Critical (15+)',
 value: criticalRisksCount.toString(),
 ),
 ),
 const SizedBox(width: 16),
 Expanded(
 child: _buildMetricCard(
 icon: Icons.show_chart_rounded,
 iconColor: const Color(0xFF8B5CF6),
 iconBg: const Color(0xFFF3E8FF),
 label: 'Avg Risk Score',
 value: avgRiskScore.toString(),
 ),
 ),
 const SizedBox(width: 16),
 Expanded(
 child: _buildMetricCard(
 icon: Icons.shield_rounded,
 iconColor: const Color(0xFF10B981),
 iconBg: const Color(0xFFD1FAE5),
 label: 'Mitigations',
 value: _mitigations.length.toString(),
 ),
 ),
 ],
 );
 }

 Widget _buildMetricCard({
 required IconData icon,
 required Color iconColor,
 required Color iconBg,
 required String label,
 required String value,
 }) {
 return Container(
 padding: const EdgeInsets.all(20),
 decoration: BoxDecoration(
 color: Colors.white,
 borderRadius: BorderRadius.circular(16),
 border: Border.all(color: const Color(0xFFE5E7EB)),
 ),
 child: Row(
 children: [
 Container(
 width: 48,
 height: 48,
 decoration: BoxDecoration(
 color: iconBg,
 borderRadius: BorderRadius.circular(12),
 ),
 child: Icon(icon, size: 24, color: iconColor),
 ),
 const SizedBox(width: 16),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Text(
 value,
 style: const TextStyle(
 fontSize: 28,
 fontWeight: FontWeight.w800,
 color: Color(0xFF111827),
 ),
 ),
 Text(
 label,
 style: const TextStyle(
 fontSize: 13,
 fontWeight: FontWeight.w600,
 color: Color(0xFF6B7280),
 ),
 ),
 ],
 ),
 ),
 ],
 ),
 );
 }

 Widget _buildRiskRegister(bool isMobile) {
 return _buildSectionCard(
 icon: Icons.assignment_late_rounded,
 iconColor: const Color(0xFFEF4444),
 iconBg: const Color(0xFFFEE2E2),
 title: 'Risk Register',
 subtitle:
 'Track and monitor all identified project risks with scores and mitigation',
 actionLabel: 'Add Risk',
 onAction: _showRiskEditor,
 child: _filteredRisks.isEmpty
 ? _buildEmptyState(
 icon: Icons.warning_amber_outlined,
 title: 'No risks tracked yet',
 description:
 'Add risks manually or generate AI drafts to get started.',
 )
 : isMobile
 ? Column(
 children: _filteredRisks
 .map((risk) => _buildRiskCard(risk))
 .toList(),
 )
 : _buildRiskTable(),
 );
 }

 Widget _buildRiskTable() {
 return Container(
 decoration: BoxDecoration(
 color: Colors.white,
 borderRadius: BorderRadius.circular(12),
 border: Border.all(color: const Color(0xFFE5E7EB)),
 ),
 child: DataTable(
 headingRowColor: WidgetStateProperty.all(const Color(0xFFF9FAFB)),
 dataRowMaxHeight: 80,
 columnSpacing: 12,
 columns: const [
 DataColumn(
 label: Text('Risk',
 style: TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151))),
 ),
 DataColumn(
 label: Text('Category',
 style: TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151))),
 ),
 DataColumn(
 label: Text('Score',
 style: TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151))),
 ),
 DataColumn(
 label: Text('L/I',
 style: TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151))),
 ),
 DataColumn(
 label: Text('Owner',
 style: TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151))),
 ),
 DataColumn(
 label: Text('Status',
 style: TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151))),
 ),
 DataColumn(
 label: Text('Next Review',
 style: TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151))),
 ),
 DataColumn(
 label: Text('Actions',
 style: TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151))),
 ),
 ],
 rows: _filteredRisks.map((risk) {
 final statusColor = _getStatusColor(risk.status);
 final scoreColor = _getRiskScoreColor(risk.riskScore);

 return DataRow(
 color: WidgetStateProperty.all(Colors.white),
 cells: [
 DataCell(
 SizedBox(
 width: 180,
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 mainAxisAlignment: MainAxisAlignment.center,
 children: [
 Text(
 risk.title,
 style: const TextStyle(
 fontSize: 13,
 fontWeight: FontWeight.w700,
 color: Color(0xFF111827),
 ),
 maxLines: 2,
 overflow: TextOverflow.ellipsis,
 ),
 if (risk.description.isNotEmpty) ...[
 const SizedBox(height: 2),
 Text(
 risk.description,
 style: const TextStyle(
 fontSize: 11,
 color: Color(0xFF9CA3AF),
 ),
 maxLines: 1,
 overflow: TextOverflow.ellipsis,
 ),
 ],
 ],
 ),
 ),
 ),
 DataCell(
 _buildCategoryBadge(risk.category),
 ),
 DataCell(
 _buildRiskScoreBadge(risk.riskScore, scoreColor),
 ),
 DataCell(
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 Text(
 '${risk.likelihoodScore}',
 style: TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w700,
 color: _getScoreColor(risk.likelihoodScore),
 ),
 ),
 const Text('/',
 style:
 TextStyle(fontSize: 11, color: Color(0xFF9CA3AF))),
 Text(
 '${risk.impactScore}',
 style: TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w700,
 color: _getScoreColor(risk.impactScore),
 ),
 ),
 ],
 ),
 ),
 DataCell(
 SizedBox(
 width: 100,
 child: Text(
 risk.owner,
 style: const TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w600,
 color: Color(0xFF4B5563),
 ),
 overflow: TextOverflow.ellipsis,
 ),
 ),
 ),
 DataCell(_buildStatusBadge(risk.status, statusColor)),
 DataCell(
 Text(
 _formatDateShort(risk.nextReview),
 style: const TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w600,
 color: Color(0xFF6B7280),
 ),
 ),
 ),
 DataCell(
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 _buildEditButton(() => _showRiskEditor(existing: risk)),
 const SizedBox(width: 6),
 _buildDeleteButton(() => _deleteRisk(risk.id)),
 ],
 ),
 ),
 ],
 );
 }).toList(),
 ),
 );
 }

 Widget _buildRiskCard(_RiskData risk) {
 final statusColor = _getStatusColor(risk.status);
 final scoreColor = _getRiskScoreColor(risk.riskScore);

 return Container(
 margin: const EdgeInsets.only(bottom: 12),
 padding: const EdgeInsets.all(16),
 decoration: BoxDecoration(
 color: Colors.white,
 borderRadius: BorderRadius.circular(16),
 border: Border.all(color: const Color(0xFFE5E7EB)),
 ),
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Row(
 children: [
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Text(
 risk.title,
 style: const TextStyle(
 fontSize: 16,
 fontWeight: FontWeight.w800,
 color: Color(0xFF111827),
 ),
 ),
 if (risk.description.isNotEmpty) ...[
 const SizedBox(height: 4),
 Text(
 risk.description,
 style: const TextStyle(
 fontSize: 13,
 color: Color(0xFF6B7280),
 ),
 maxLines: 2,
 overflow: TextOverflow.ellipsis,
 ),
 ],
 ],
 ),
 ),
 _buildEditButton(() => _showRiskEditor(existing: risk)),
 const SizedBox(width: 8),
 _buildDeleteButton(() => _deleteRisk(risk.id)),
 ],
 ),
 const SizedBox(height: 12),
 Row(
 children: [
 _buildRiskScoreBadge(risk.riskScore, scoreColor),
 const SizedBox(width: 8),
 _buildCategoryBadge(risk.category),
 const SizedBox(width: 8),
 _buildStatusBadge(risk.status, statusColor),
 ],
 ),
 const SizedBox(height: 12),
 Wrap(
 spacing: 12,
 runSpacing: 8,
 children: [
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.person_outline,
 size: 14, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 risk.owner,
 style: const TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w600,
 color: Color(0xFF4B5563),
 ),
 ),
 ],
 ),
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.calendar_today_outlined,
 size: 14, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 _formatDateShort(risk.nextReview),
 style: const TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w600,
 color: Color(0xFF4B5563),
 ),
 ),
 ],
 ),
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.shield_outlined,
 size: 14, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 'L:${risk.likelihoodScore}/I:${risk.impactScore}',
 style: const TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF4B5563),
 ),
 ),
 ],
 ),
 ],
 ),
 ],
 ),
 );
 }

 Widget _buildRiskSignals() {
 return _buildSectionCard(
 icon: Icons.sensors_rounded,
 iconColor: const Color(0xFFF97316),
 iconBg: const Color(0xFFFFEDD5),
 title: 'Risk Signals',
 subtitle: 'Early warnings and indicators from the field',
 actionLabel: 'Add Signal',
 onAction: _showSignalEditor,
 child: _signals.isEmpty
 ? _buildEmptyState(
 icon: Icons.sensors_outlined,
 title: 'No signals yet',
 description: 'Risk signals and alerts will appear here.',
 )
 : Column(
 children:
 _signals.map((signal) => _buildSignalCard(signal)).toList(),
 ),
 );
 }

 Widget _buildSignalCard(_SignalData signal) {
 final severityColor = _getSeverityColor(signal.severity);
 final associatedRisk = _risks.firstWhere(
 (r) => r.id == signal.associatedRiskId,
 orElse: () => _RiskData.empty(),
 );

 return Container(
 margin: const EdgeInsets.only(bottom: 12),
 padding: const EdgeInsets.all(16),
 decoration: BoxDecoration(
 color: Colors.white,
 borderRadius: BorderRadius.circular(16),
 border: Border.all(color: const Color(0xFFE5E7EB)),
 ),
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Row(
 children: [
 Container(
 width: 40,
 height: 40,
 decoration: BoxDecoration(
 color: severityColor.withOpacity(0.15),
 borderRadius: BorderRadius.circular(10),
 ),
 child: Icon(
 _getSeverityIcon(signal.severity),
 size: 20,
 color: severityColor,
 ),
 ),
 const SizedBox(width: 12),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Text(
 signal.title,
 style: const TextStyle(
 fontSize: 14,
 fontWeight: FontWeight.w700,
 color: Color(0xFF111827),
 ),
 ),
 if (signal.source.isNotEmpty) ...[
 const SizedBox(height: 2),
 Text(
 'Source: ${signal.source}',
 style: const TextStyle(
 fontSize: 11,
 color: Color(0xFF9CA3AF),
 ),
 ),
 ],
 ],
 ),
 ),
 _buildStatusBadge(signal.severity, severityColor),
 const SizedBox(width: 8),
 _buildEditButton(() => _showSignalEditor(existing: signal)),
 const SizedBox(width: 6),
 _buildDeleteButton(() => _deleteSignal(signal.id)),
 ],
 ),
 if (signal.detail.isNotEmpty) ...[
 const SizedBox(height: 10),
 Text(
 signal.detail,
 style: const TextStyle(
 fontSize: 13,
 color: Color(0xFF6B7280),
 height: 1.4,
 ),
 ),
 ],
 const SizedBox(height: 10),
 Wrap(
 spacing: 12,
 runSpacing: 6,
 children: [
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.event_outlined,
 size: 13, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 _formatDateShort(signal.dateDetected),
 style: const TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w600,
 color: Color(0xFF6B7280),
 ),
 ),
 ],
 ),
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.verified_outlined,
 size: 13, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 'Confidence: ${signal.confidenceLevel}',
 style: const TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w600,
 color: Color(0xFF6B7280),
 ),
 ),
 ],
 ),
 if (associatedRisk.id.isNotEmpty) ...[
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.link_outlined,
 size: 13, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 'Linked: ${associatedRisk.title}',
 style: const TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w600,
 color: Color(0xFF6366F1),
 ),
 maxLines: 1,
 overflow: TextOverflow.ellipsis,
 ),
 ],
 ),
 ],
 ],
 ),
 ],
 ),
 );
 }

 Widget _buildMitigationPlans() {
 return _buildSectionCard(
 icon: Icons.shield_rounded,
 iconColor: const Color(0xFF10B981),
 iconBg: const Color(0xFFD1FAE5),
 title: 'Mitigation Plans',
 subtitle: 'Active mitigation strategies with progress tracking',
 actionLabel: 'Add Plan',
 onAction: _showMitigationEditor,
 child: _mitigations.isEmpty
 ? _buildEmptyState(
 icon: Icons.shield_outlined,
 title: 'No mitigation plans',
 description: 'Define mitigation strategies for identified risks.',
 )
 : Column(
 children: _mitigations
 .map((mitigation) => _buildMitigationCard(mitigation))
 .toList(),
 ),
 );
 }

 Widget _buildMitigationCard(_MitigationData mitigation) {
 final statusColor = _getMitigationStatusColor(mitigation.status);
 final associatedRisk = _risks.firstWhere(
 (r) => r.id == mitigation.associatedRiskId,
 orElse: () => _RiskData.empty(),
 );

 return Container(
 margin: const EdgeInsets.only(bottom: 12),
 padding: const EdgeInsets.all(16),
 decoration: BoxDecoration(
 color: Colors.white,
 borderRadius: BorderRadius.circular(16),
 border: Border.all(color: const Color(0xFFE5E7EB)),
 ),
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Row(
 children: [
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Text(
 mitigation.title,
 style: const TextStyle(
 fontSize: 15,
 fontWeight: FontWeight.w700,
 color: Color(0xFF111827),
 ),
 ),
 if (mitigation.description.isNotEmpty) ...[
 const SizedBox(height: 4),
 Text(
 mitigation.description,
 style: const TextStyle(
 fontSize: 12,
 color: Color(0xFF6B7280),
 ),
 maxLines: 2,
 overflow: TextOverflow.ellipsis,
 ),
 ],
 ],
 ),
 ),
 _buildStatusBadge(mitigation.status, statusColor),
 const SizedBox(width: 10),
 _buildEditButton(
 () => _showMitigationEditor(existing: mitigation)),
 const SizedBox(width: 6),
 _buildDeleteButton(() => _deleteMitigation(mitigation.id)),
 ],
 ),
 const SizedBox(height: 12),
 ClipRRect(
 borderRadius: BorderRadius.circular(8),
 child: LinearProgressIndicator(
 value: mitigation.progress / 100,
 backgroundColor: const Color(0xFFE5E7EB),
 valueColor: AlwaysStoppedAnimation<Color>(
 _getProgressColor(mitigation.progress),
 ),
 minHeight: 6,
 ),
 ),
 const SizedBox(height: 8),
 Row(
 mainAxisAlignment: MainAxisAlignment.spaceBetween,
 children: [
 Text(
 '${mitigation.progress}% complete',
 style: const TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w700,
 color: Color(0xFF6B7280),
 ),
 ),
 if (mitigation.estimatedCost.isNotEmpty &&
 mitigation.estimatedCost != '0') ...[
 Row(
 children: [
 const Icon(Icons.payments_outlined,
 size: 13, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 '\$${mitigation.estimatedCost}',
 style: const TextStyle(
 fontSize: 12,
 fontWeight: FontWeight.w600,
 color: Color(0xFF6B7280),
 ),
 ),
 ],
 ),
 ],
 ],
 ),
 const SizedBox(height: 10),
 Wrap(
 spacing: 12,
 runSpacing: 6,
 children: [
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.person_outline,
 size: 13, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 mitigation.owner,
 style: const TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w600,
 color: Color(0xFF6B7280),
 ),
 ),
 ],
 ),
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.calendar_today_outlined,
 size: 13, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 _formatDateShort(mitigation.dueDate),
 style: const TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w600,
 color: Color(0xFF6B7280),
 ),
 ),
 ],
 ),
 if (associatedRisk.id.isNotEmpty) ...[
 Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.link_outlined,
 size: 13, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 4),
 Text(
 'Risk: ${associatedRisk.title}',
 style: const TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w600,
 color: Color(0xFF6366F1),
 ),
 maxLines: 1,
 overflow: TextOverflow.ellipsis,
 ),
 ],
 ),
 ],
 ],
 ),
 if (mitigation.statusNotes.isNotEmpty) ...[
 const SizedBox(height: 8),
 Container(
 padding: const EdgeInsets.all(10),
 decoration: BoxDecoration(
 color: const Color(0xFFF9FAFB),
 borderRadius: BorderRadius.circular(8),
 ),
 child: Row(
 children: [
 const Icon(Icons.note_outlined,
 size: 14, color: Color(0xFF9CA3AF)),
 const SizedBox(width: 6),
 Expanded(
 child: Text(
 mitigation.statusNotes,
 style: const TextStyle(
 fontSize: 11,
 color: Color(0xFF6B7280),
 fontStyle: FontStyle.italic,
 ),
 maxLines: 2,
 overflow: TextOverflow.ellipsis,
 ),
 ),
 ],
 ),
 ),
 ],
 ],
 ),
 );
 }

 Widget _buildSectionCard({
 required IconData icon,
 required Color iconColor,
 required Color iconBg,
 required String title,
 required String subtitle,
 required Widget child,
 String? actionLabel,
 VoidCallback? onAction,
 }) {
 return Container(
 padding: const EdgeInsets.all(20),
 decoration: BoxDecoration(
 color: Colors.white,
 borderRadius: BorderRadius.circular(20),
 border: Border.all(color: const Color(0xFFE5E7EB)),
 ),
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Row(
 children: [
 Container(
 width: 48,
 height: 48,
 decoration: BoxDecoration(
 color: iconBg,
 borderRadius: BorderRadius.circular(12),
 ),
 child: Icon(icon, size: 24, color: iconColor),
 ),
 const SizedBox(width: 16),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Text(
 title,
 style: const TextStyle(
 fontSize: 18,
 fontWeight: FontWeight.w800,
 color: Color(0xFF111827),
 ),
 ),
 Text(
 subtitle,
 style: const TextStyle(
 fontSize: 13,
 fontWeight: FontWeight.w500,
 color: Color(0xFF6B7280),
 ),
 ),
 ],
 ),
 ),
 if (actionLabel != null && onAction != null)
 Material(
 color: const Color(0xFF6366F1),
 borderRadius: BorderRadius.circular(10),
 child: InkWell(
 onTap: onAction,
 borderRadius: BorderRadius.circular(10),
 child: Container(
 padding: const EdgeInsets.symmetric(
 horizontal: 14,
 vertical: 10,
 ),
 child: Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 const Icon(Icons.add, size: 16, color: Colors.white),
 const SizedBox(width: 6),
 Text(
 actionLabel,
 style: const TextStyle(
 fontSize: 13,
 fontWeight: FontWeight.w600,
 color: Colors.white,
 ),
 ),
 ],
 ),
 ),
 ),
 ),
 ],
 ),
 const SizedBox(height: 20),
 child,
 ],
 ),
 );
 }

 Widget _buildEmptyState({
 required IconData icon,
 required String title,
 required String description,
 }) {
 return Container(
 padding: const EdgeInsets.all(40),
 decoration: BoxDecoration(
 color: const Color(0xFFF9FAFB),
 borderRadius: BorderRadius.circular(16),
 ),
 child: Column(
 children: [
 Icon(icon, size: 48, color: const Color(0xFF9CA3AF)),
 const SizedBox(height: 16),
 Text(
 title,
 style: const TextStyle(
 fontSize: 16,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151),
 ),
 ),
 const SizedBox(height: 8),
 Text(
 description,
 style: const TextStyle(
 fontSize: 14,
 color: Color(0xFF6B7280),
 ),
 textAlign: TextAlign.center,
 ),
 ],
 ),
 );
 }

 Widget _buildStatusBadge(String label, Color color) {
 return Container(
 padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
 decoration: BoxDecoration(
 color: color.withOpacity(0.12),
 borderRadius: BorderRadius.circular(5),
 ),
 child: Text(
 label,
 style: TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w700,
 color: color,
 ),
 ),
 );
 }

 Widget _buildCategoryBadge(String category) {
 return Container(
 padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
 decoration: BoxDecoration(
 color: const Color(0xFFE0E7FF),
 borderRadius: BorderRadius.circular(5),
 ),
 child: Text(
 category,
 style: const TextStyle(
 fontSize: 10,
 fontWeight: FontWeight.w700,
 color: Color(0xFF4F46E5),
 ),
 ),
 );
 }

 Widget _buildRiskScoreBadge(int score, Color color) {
 return Container(
 padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
 decoration: BoxDecoration(
 color: color.withOpacity(0.15),
 borderRadius: BorderRadius.circular(5),
 border: Border.all(color: color, width: 1),
 ),
 child: Row(
 mainAxisSize: MainAxisSize.min,
 children: [
 Text(
 'Score: $score',
 style: TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w800,
 color: color,
 ),
 ),
 ],
 ),
 );
 }

 Widget _buildEditButton(VoidCallback onTap) {
 return Material(
 color: const Color(0xFFF3F4F6),
 borderRadius: BorderRadius.circular(8),
 child: InkWell(
 onTap: onTap,
 borderRadius: BorderRadius.circular(8),
 child: Container(
 padding: const EdgeInsets.all(7),
 child: const Icon(Icons.edit_outlined,
 size: 14, color: Color(0xFF4B5563)),
 ),
 ),
 );
 }

 Widget _buildDeleteButton(VoidCallback onTap) {
 return Material(
 color: const Color(0xFFFEE2E2),
 borderRadius: BorderRadius.circular(8),
 child: InkWell(
 onTap: onTap,
 borderRadius: BorderRadius.circular(8),
 child: Container(
 padding: const EdgeInsets.all(7),
 child: const Icon(Icons.delete_outline,
 size: 14, color: Color(0xFFEF4444)),
 ),
 ),
 );
 }

 Color _getStatusColor(String status) {
 switch (status.toLowerCase()) {
 case 'open':
 return const Color(0xFFF59E0B);
 case 'at risk':
 case 'blocked':
 return const Color(0xFFEF4444);
 case 'closed':
 case 'resolved':
 return const Color(0xFF10B981);
 case 'monitoring':
 case 'in progress':
 return const Color(0xFF6366F1);
 default:
 return const Color(0xFF6B7280);
 }
 }

 Color _getSeverityColor(String severity) {
 switch (severity.toLowerCase()) {
 case 'critical':
 case 'high':
 return const Color(0xFFEF4444);
 case 'medium':
 return const Color(0xFFF59E0B);
 case 'low':
 return const Color(0xFF10B981);
 default:
 return const Color(0xFF6B7280);
 }
 }

 Color _getMitigationStatusColor(String status) {
 switch (status.toLowerCase()) {
 case 'complete':
 case 'completed':
 return const Color(0xFF10B981);
 case 'in progress':
 return const Color(0xFF6366F1);
 case 'planning':
 return const Color(0xFFF59E0B);
 case 'blocked':
 return const Color(0xFFEF4444);
 default:
 return const Color(0xFF6B7280);
 }
 }

 Color _getRiskScoreColor(int score) {
 if (score >= 15) return const Color(0xFFDC2626);
 if (score >= 10) return const Color(0xFFF97316);
 if (score >= 5) return const Color(0xFFF59E0B);
 return const Color(0xFF10B981);
 }

 Color _getScoreColor(int score) {
 if (score >= 4) return const Color(0xFFDC2626);
 if (score >= 3) return const Color(0xFFF97316);
 if (score >= 2) return const Color(0xFFF59E0B);
 return const Color(0xFF10B981);
 }

 Color _getProgressColor(int progress) {
 if (progress >= 80) return const Color(0xFF10B981);
 if (progress >= 50) return const Color(0xFF6366F1);
 if (progress >= 25) return const Color(0xFFF59E0B);
 return const Color(0xFFEF4444);
 }

 IconData _getSeverityIcon(String severity) {
 switch (severity.toLowerCase()) {
 case 'critical':
 case 'high':
 return Icons.error_rounded;
 case 'medium':
 return Icons.warning_rounded;
 case 'low':
 return Icons.info_rounded;
 default:
 return Icons.info_outline;
 }
 }

 String _formatDateShort(String dateStr) {
 if (dateStr == 'TBD' || dateStr.isEmpty) return 'TBD';
 try {
 final parts = dateStr.split('-');
 if (parts.length == 3) {
 return '${parts[1]}/${parts[2]}';
 }
 } catch (e) { debugPrint('Error: $e'); }
 return dateStr;
 }

 Future<void> _showRiskEditor({_RiskData? existing}) async {
 final titleController = TextEditingController(text: existing?.title ?? '');
 final descriptionController =
 TextEditingController(text: existing?.description ?? '');
 final ownerController = TextEditingController(text: existing?.owner ?? '');
 final categoryController =
 TextEditingController(text: existing?.category ?? '');
 final reviewController =
 TextEditingController(text: existing?.nextReview ?? '');
 final triggerController =
 TextEditingController(text: existing?.triggerEvents ?? '');
 final mitigationStrategyController =
 TextEditingController(text: existing?.mitigationStrategy ?? '');
 final associatedMitigationController =
 TextEditingController(text: existing?.associatedMitigation ?? '');
 final formKey = GlobalKey<FormState>();
 int likelihoodScore = existing?.likelihoodScore ?? 3;
 int impactScore = existing?.impactScore ?? 3;
 String probability = existing?.probability ?? 'Medium';
 String impact = existing?.impact ?? 'Medium';
 String status = existing?.status ?? 'Open';

 final result = await showDialog<bool>(
 context: context,
 builder: (context) => StatefulBuilder(
 builder: (context, setDialogState) => Dialog(
 shape:
 RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
 child: ConstrainedBox(
 constraints: const BoxConstraints(maxWidth: 600, maxHeight: 700),
 child: SingleChildScrollView(
 padding: const EdgeInsets.all(24),
 child: Form(
 key: formKey,
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 mainAxisSize: MainAxisSize.min,
 children: [
 Row(
 children: [
 Container(
 width: 40,
 height: 40,
 decoration: BoxDecoration(
 color: const Color(0xFFFEE2E2),
 borderRadius: BorderRadius.circular(10),
 ),
 child: const Icon(Icons.warning_amber_rounded,
 size: 22, color: Color(0xFFEF4444)),
 ),
 const SizedBox(width: 12),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Text(
 existing == null ? 'Add New Risk' : 'Edit Risk',
 style: const TextStyle(
 fontSize: 20,
 fontWeight: FontWeight.w800,
 color: Color(0xFF111827),
 ),
 ),
 Text(
 'Fill in the risk details below',
 style: TextStyle(
 fontSize: 13,
 color: Color(0xFF6B7280),
 ),
 ),
 ],
 ),
 ),
 IconButton(
 onPressed: () => Navigator.pop(context, false),
 icon: const Icon(Icons.close),
 ),
 ],
 ),
 const SizedBox(height: 12),
 Row(
 children: [
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 const Text('Likelihood',
 style: TextStyle(fontSize: 11, fontWeight: FontWeight.w600)),
 const SizedBox(height: 8),
 Row(
 children: List.generate(5, (index) {
 final value = index + 1;
 final isSelected = likelihoodScore == value;
 return Padding(
 padding: const EdgeInsets.only(right: 6),
 child: InkWell(
 onTap: () => setDialogState(() => likelihoodScore = value),
 child: Container(
 width: 36,
 height: 36,
 decoration: BoxDecoration(
 color: isSelected
 ? _getScoreColor(value)
 : Colors.white,
 border: Border.all(
 color: isSelected
 ? _getScoreColor(value)
 : const Color(0xFFD1D5DB),
 ),
 borderRadius: BorderRadius.circular(8),
 ),
 child: Center(
 child: Text(
 '$value',
 style: TextStyle(
 fontSize: 14,
 fontWeight: FontWeight.w700,
 color: isSelected ? Colors.white : const Color(0xFF374151),
 ),
 ),
 ),
 ),
 ),
 );
 }),
 ),
 ],
 ),
 ),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 const Text('Impact',
 style: TextStyle(fontSize: 11, fontWeight: FontWeight.w600)),
 const SizedBox(height: 8),
 Row(
 children: List.generate(5, (index) {
 final value = index + 1;
 final isSelected = impactScore == value;
 return Padding(
 padding: const EdgeInsets.only(right: 6),
 child: InkWell(
 onTap: () => setDialogState(() => impactScore = value),
 child: Container(
 width: 36,
 height: 36,
 decoration: BoxDecoration(
 color: isSelected
 ? _getScoreColor(value)
 : Colors.white,
 border: Border.all(
 color: isSelected
 ? _getScoreColor(value)
 : const Color(0xFFD1D5DB),
 ),
 borderRadius: BorderRadius.circular(8),
 ),
 child: Center(
 child: Text(
 '$value',
 style: TextStyle(
 fontSize: 14,
 fontWeight: FontWeight.w700,
 color: isSelected ? Colors.white : const Color(0xFF374151),
 ),
 ),
 ),
 ),
 ),
 );
 }),
 ),
 ],
 ),
 ),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 const Text('Risk Score',
 style: TextStyle(fontSize: 11, fontWeight: FontWeight.w600)),
 const SizedBox(height: 8),
 Container(
 padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
 decoration: BoxDecoration(
 color: _getRiskScoreColor(likelihoodScore * impactScore).withOpacity(0.15),
 border: Border.all(
 color: _getRiskScoreColor(likelihoodScore * impactScore),
 ),
 borderRadius: BorderRadius.circular(8),
 ),
 child: Text(
 '${likelihoodScore * impactScore}',
 style: TextStyle(
 fontSize: 20,
 fontWeight: FontWeight.w800,
 color: _getRiskScoreColor(likelihoodScore * impactScore),
 ),
 ),
 ),
 ],
 ),
 ),
 ],
 ),
 const SizedBox(height: 20),
 VoiceTextFormField(
 controller: titleController,
 decoration: _inputDecoration(
 'Risk Title *', Icons.warning_amber_outlined),
 textCapitalization: TextCapitalization.sentences,
 validator: (value) =>
 value == null || value.trim().isEmpty
 ? 'Required'
 : null,
 ),
 const SizedBox(height: 14),
 VoiceTextFormField(
 controller: descriptionController,
 maxLines: 2,
 decoration: _inputDecoration(
 'Description', Icons.description_outlined),
 textCapitalization: TextCapitalization.sentences,
 ),
 const SizedBox(height: 14),
 Row(
 children: [
 Expanded(
 child: VoiceTextFormField(
 controller: categoryController,
 decoration: _inputDecoration(
 'Category', Icons.category_outlined),
 textCapitalization: TextCapitalization.words,
 ),
 ),
 const SizedBox(width: 14),
 Expanded(
 child: VoiceTextFormField(
 controller: ownerController,
 decoration:
 _inputDecoration('Owner', Icons.person_outline),
 textCapitalization: TextCapitalization.words,
 ),
 ),
 ],
 ),
 const SizedBox(height: 14),
 Container(
 padding: const EdgeInsets.all(16),
 decoration: BoxDecoration(
 color: const Color(0xFFF9FAFB),
 borderRadius: BorderRadius.circular(12),
 border: Border.all(color: const Color(0xFFE5E7EB)),
 ),
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 const Text(
 'Risk Assessment (1-5)',
 style: TextStyle(
 fontSize: 13,
 fontWeight: FontWeight.w700,
 color: Color(0xFF374151),
 ),
 ),
 const SizedBox(height: 12),
 Row(
 children: [
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 const Text('Likelihood',
 style: TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w600)),
 const SizedBox(height: 8),
 Row(
 children: List.generate(5, (index) {
 final value = index + 1;
 final isSelected =
 likelihoodScore == value;
 return Padding(
 padding:
 const EdgeInsets.only(right: 6),
 child: InkWell(
 onTap: () => setDialogState(
 () => likelihoodScore = value),
 child: Container(
 width: 36,
 height: 36,
 decoration: BoxDecoration(
 color: isSelected
 ? _getScoreColor(value)
 : Colors.white,
 border: Border.all(
 color: isSelected
 ? _getScoreColor(value)
 : const Color(0xFFD1D5DB),
 ),
 borderRadius:
 BorderRadius.circular(8),
 ),
 child: Center(
 child: Text(
 '$value',
 style: TextStyle(
 fontSize: 14,
 fontWeight: FontWeight.w700,
 color: isSelected
 ? Colors.white
 : const Color(
 0xFF374151),
 ),
 ),
 ),
 ),
 ),
 );
 }),
 ),
 ],
 ),
 ),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 const Text('Impact',
 style: TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w600)),
 const SizedBox(height: 8),
 Row(
 children: List.generate(5, (index) {
 final value = index + 1;
 final isSelected = impactScore == value;
 return Padding(
 padding:
 const EdgeInsets.only(right: 6),
 child: InkWell(
 onTap: () => setDialogState(
 () => impactScore = value),
 child: Container(
 width: 36,
 height: 36,
 decoration: BoxDecoration(
 color: isSelected
 ? _getScoreColor(value)
 : Colors.white,
 border: Border.all(
 color: isSelected
 ? _getScoreColor(value)
 : const Color(0xFFD1D5DB),
 ),
 borderRadius:
 BorderRadius.circular(8),
 ),
 child: Center(
 child: Text(
 '$value',
 style: TextStyle(
 fontSize: 14,
 fontWeight: FontWeight.w700,
 color: isSelected
 ? Colors.white
 : const Color(
 0xFF374151),
 ),
 ),
 ),
 ),
 ),
 );
 }),
 ),
 ],
 ),
 ),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 const Text('Risk Score',
 style: TextStyle(
 fontSize: 11,
 fontWeight: FontWeight.w600)),
 const SizedBox(height: 8),
 Container(
 padding: const EdgeInsets.symmetric(
 horizontal: 12, vertical: 8),
 decoration: BoxDecoration(
 color: _getRiskScoreColor(
 likelihoodScore * impactScore)
 .withValues(alpha: 0.15),
 border: Border.all(
 color: _getRiskScoreColor(
 likelihoodScore * impactScore),
 ),
 borderRadius: BorderRadius.circular(8),
 ),
 child: Text(
 '${likelihoodScore * impactScore}',
 style: TextStyle(
 fontSize: 20,
 fontWeight: FontWeight.w800,
 color: _getRiskScoreColor(
 likelihoodScore * impactScore),
 ),
 ),
 ),
 ],
 ),
 ),
 ],
 ),
 ],
 ),
 ),
 const SizedBox(height: 14),
 Row(
 children: [
 Expanded(
 child: DropdownButtonFormField<String>(
 value: probability,
 items: const ['Low', 'Medium', 'High']
 .map((v) =>
 DropdownMenuItem(value: v, child: Text(v)))
 .toList(),
 onChanged: (v) => setDialogState(
 () => probability = v ?? probability),
 decoration: _inputDecoration(
 'Probability', Icons.trending_up),
 ),
 ),
 const SizedBox(width: 14),
 Expanded(
 child: DropdownButtonFormField<String>(
 value: impact,
 items: const ['Low', 'Medium', 'High', 'Critical']
 .map((v) =>
 DropdownMenuItem(value: v, child: Text(v)))
 .toList(),
 onChanged: (v) =>
 setDialogState(() => impact = v ?? impact),
 decoration:
 _inputDecoration('Impact', Icons.priority_high),
 ),
 ),
 const SizedBox(width: 14),
 Expanded(
 child: DropdownButtonFormField<String>(
 value: status,
 items: const [
 'Open',
 'Monitoring',
 'At Risk',
 'Blocked',
 'Closed'
 ]
 .map((v) =>
 DropdownMenuItem(value: v, child: Text(v)))
 .toList(),
 onChanged: (v) =>
 setDialogState(() => status = v ?? status),
 decoration: _inputDecoration(
 'Status', Icons.check_circle_outline),
 ),
 ),
 ],
 ),
 const SizedBox(height: 14),
 VoiceTextFormField(
 controller: reviewController,
 decoration: _inputDecoration(
 'Next Review Date', Icons.calendar_today),
 keyboardType: TextInputType.datetime,
 ),
 const SizedBox(height: 14),
 VoiceTextFormField(
 controller: triggerController,
 maxLines: 2,
 decoration: _inputDecoration('Trigger Events',
 Icons.notifications_active_outlined),
 textCapitalization: TextCapitalization.sentences,
 ),
 const SizedBox(height: 14),
 VoiceTextFormField(
 controller: mitigationStrategyController,
 maxLines: 2,
 decoration: _inputDecoration(
 'Mitigation Strategy', Icons.lightbulb_outline),
 textCapitalization: TextCapitalization.sentences,
 ),
 const SizedBox(height: 14),
 VoiceTextFormField(
 controller: associatedMitigationController,
 decoration:
 _inputDecoration('Associated Mitigation', Icons.link),
 textCapitalization: TextCapitalization.sentences,
 ),
 const SizedBox(height: 24),
 Row(
 mainAxisAlignment: MainAxisAlignment.end,
 children: [
 TextButton(
 onPressed: () => Navigator.pop(context, false),
 style: TextButton.styleFrom(
 padding: const EdgeInsets.symmetric(
 horizontal: 24, vertical: 14),
 shape: RoundedRectangleBorder(
 borderRadius: BorderRadius.circular(10)),
 ),
 child: const Text('Cancel',
 style: TextStyle(fontWeight: FontWeight.w600)),
 ),
 const SizedBox(width: 12),
 FilledButton(
 onPressed: () {
 if (!(formKey.currentState?.validate() ?? false)) {
 return;
 }
 Navigator.pop(context, true);
 },
 style: FilledButton.styleFrom(
 backgroundColor: const Color(0xFF6366F1),
 padding: const EdgeInsets.symmetric(
 horizontal: 28, vertical: 14),
 shape: RoundedRectangleBorder(
 borderRadius: BorderRadius.circular(10)),
 ),
 child: Text(
 existing == null ? 'Add Risk' : 'Save Changes',
 style:
 const TextStyle(fontWeight: FontWeight.w600)),
 ),
 ],
 ),
 ],
 ),
 ),
 ),
 ),
 ),
 ),
 );

 titleController.dispose();
 descriptionController.dispose();
 ownerController.dispose();
 categoryController.dispose();
 reviewController.dispose();
 triggerController.dispose();
 mitigationStrategyController.dispose();
 associatedMitigationController.dispose();

 if (result != true || !mounted) return;

 final newRisk = _RiskData(
 id: existing?.id ?? DateTime.now().microsecondsSinceEpoch.toString(),
 title: titleController.text.trim(),
 description: descriptionController.text.trim(),
 category: categoryController.text.trim().isEmpty
 ? 'General'
 : categoryController.text.trim(),
 owner: ownerController.text.trim().isEmpty
 ? 'Unassigned'
 : ownerController.text.trim(),
 likelihoodScore: likelihoodScore,
 impactScore: impactScore,
 probability: probability,
 impact: impact,
 riskScore: likelihoodScore * impactScore,
 status: status,
 triggerEvents: triggerController.text.trim(),
 mitigationStrategy: mitigationStrategyController.text.trim(),
 nextReview: reviewController.text.trim().isEmpty
 ? 'TBD'
 : reviewController.text.trim(),
 associatedMitigation: associatedMitigationController.text.trim(),
 createdAt: existing?.createdAt ?? _formatDate(DateTime.now()),
 lastModified: _formatDate(DateTime.now()),
 );

 setState(() {
 final index = _risks.indexWhere((r) => r.id == newRisk.id);
 if (index == -1) {
 _risks.insert(0, newRisk);
 } else {
 _risks[index] = newRisk;
 }
 });
 _saveToFirestore();
 }

 Future<void> _showSignalEditor({_SignalData? existing}) async {
 final titleController = TextEditingController(text: existing?.title ?? '');
 final detailController =
 TextEditingController(text: existing?.detail ?? '');
 final sourceController =
 TextEditingController(text: existing?.source ?? '');
 final dateDetectedController = TextEditingController(
 text: existing?.dateDetected ?? _formatDate(DateTime.now()));
 final associatedRiskIdController =
 TextEditingController(text: existing?.associatedRiskId ?? '');
 final formKey = GlobalKey<FormState>();
 String severity = existing?.severity ?? 'Medium';
 String confidenceLevel = existing?.confidenceLevel ?? 'Medium';

 final result = await showDialog<bool>(
 context: context,
 builder: (context) => StatefulBuilder(
 builder: (context, setDialogState) => Dialog(
 shape:
 RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
 child: ConstrainedBox(
 constraints: const BoxConstraints(maxWidth: 500),
 child: SingleChildScrollView(
 padding: const EdgeInsets.all(24),
 child: Form(
 key: formKey,
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 mainAxisSize: MainAxisSize.min,
 children: [
 Row(
 children: [
 Container(
 width: 40,
 height: 40,
 decoration: BoxDecoration(
 color: const Color(0xFFFFEDD5),
 borderRadius: BorderRadius.circular(10),
 ),
 child: const Icon(Icons.sensors_rounded,
 size: 22, color: Color(0xFFF97316)),
 ),
 const SizedBox(width: 12),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Text(
 existing == null
 ? 'Add Risk Signal'
 : 'Edit Risk Signal',
 style: const TextStyle(
 fontSize: 20,
 fontWeight: FontWeight.w800,
 color: Color(0xFF111827),
 ),
 ),
 const Text('Early warning indicators',
 style: TextStyle(
 fontSize: 13, color: Color(0xFF6B7280))),
 ],
 ),
 ),
 IconButton(
 onPressed: () => Navigator.pop(context, false),
 icon: const Icon(Icons.close),
 ),
 ],
 ),
 const SizedBox(height: 20),
 VoiceTextFormField(
 controller: titleController,
 decoration:
 _inputDecoration('Signal Title *', Icons.sensors),
 textCapitalization: TextCapitalization.sentences,
 validator: (value) =>
 value == null || value.trim().isEmpty
 ? 'Required'
 : null,
 ),
 const SizedBox(height: 14),
 VoiceTextFormField(
 controller: detailController,
 maxLines: 3,
 decoration: _inputDecoration(
 'Details', Icons.description_outlined),
 textCapitalization: TextCapitalization.sentences,
 ),
 const SizedBox(height: 14),
 Row(
 children: [
 Expanded(
 child: VoiceTextFormField(
 controller: sourceController,
 decoration: _inputDecoration(
 'Source', Icons.source_outlined),
 textCapitalization: TextCapitalization.words,
 ),
 ),
 const SizedBox(width: 14),
 Expanded(
 child: VoiceTextFormField(
 controller: dateDetectedController,
 decoration: _inputDecoration(
 'Date Detected', Icons.calendar_today),
 keyboardType: TextInputType.datetime,
 ),
 ),
 ],
 ),
 const SizedBox(height: 14),
 Row(
 children: [
 Expanded(
 child: DropdownButtonFormField<String>(
 value: severity,
 items: const ['Low', 'Medium', 'High', 'Critical']
 .map((v) =>
 DropdownMenuItem(value: v, child: Text(v)))
 .toList(),
 onChanged: (v) =>
 setDialogState(() => severity = v ?? severity),
 decoration: _inputDecoration(
 'Severity', Icons.priority_high),
 ),
 ),
 const SizedBox(width: 14),
 Expanded(
 child: DropdownButtonFormField<String>(
 value: confidenceLevel,
 items: const ['Low', 'Medium', 'High']
 .map((v) =>
 DropdownMenuItem(value: v, child: Text(v)))
 .toList(),
 onChanged: (v) => setDialogState(
 () => confidenceLevel = v ?? confidenceLevel),
 decoration: _inputDecoration(
 'Confidence', Icons.verified_outlined),
 ),
 ),
 ],
 ),
 const SizedBox(height: 14),
 DropdownButtonFormField<String>(
 value: associatedRiskIdController.text.isEmpty
 ? null
 : associatedRiskIdController.text,
 items: _risks
 .map((r) => DropdownMenuItem(
 value: r.id,
 child: Text(r.title,
 maxLines: 1,
 overflow: TextOverflow.ellipsis),
 ))
 .toList(),
 onChanged: (v) => setDialogState(
 () => associatedRiskIdController.text = v ?? ''),
 decoration:
 _inputDecoration('Associated Risk', Icons.link),
 hint: const Text('Link to a risk'),
 ),
 const SizedBox(height: 24),
 Row(
 mainAxisAlignment: MainAxisAlignment.end,
 children: [
 TextButton(
 onPressed: () => Navigator.pop(context, false),
 style: TextButton.styleFrom(
 padding: const EdgeInsets.symmetric(
 horizontal: 24, vertical: 14),
 shape: RoundedRectangleBorder(
 borderRadius: BorderRadius.circular(10)),
 ),
 child: const Text('Cancel',
 style: TextStyle(fontWeight: FontWeight.w600)),
 ),
 const SizedBox(width: 12),
 FilledButton(
 onPressed: () {
 if (!(formKey.currentState?.validate() ?? false)) {
 return;
 }
 Navigator.pop(context, true);
 },
 style: FilledButton.styleFrom(
 backgroundColor: const Color(0xFF6366F1),
 padding: const EdgeInsets.symmetric(
 horizontal: 28, vertical: 14),
 shape: RoundedRectangleBorder(
 borderRadius: BorderRadius.circular(10)),
 ),
 child: Text(
 existing == null ? 'Add Signal' : 'Save Changes',
 style:
 const TextStyle(fontWeight: FontWeight.w600)),
 ),
 ],
 ),
 ],
 ),
 ),
 ),
 ),
 ),
 ),
 );

 titleController.dispose();
 detailController.dispose();
 sourceController.dispose();
 dateDetectedController.dispose();
 associatedRiskIdController.dispose();

 if (result != true || !mounted) return;

 final newSignal = _SignalData(
 id: existing?.id ?? DateTime.now().microsecondsSinceEpoch.toString(),
 title: titleController.text.trim(),
 detail: detailController.text.trim(),
 severity: severity,
 source: sourceController.text.trim(),
 dateDetected: dateDetectedController.text.trim().isEmpty
 ? _formatDate(DateTime.now())
 : dateDetectedController.text.trim(),
 confidenceLevel: confidenceLevel,
 associatedRiskId: associatedRiskIdController.text.trim(),
 );

 setState(() {
 final index = _signals.indexWhere((s) => s.id == newSignal.id);
 if (index == -1) {
 _signals.insert(0, newSignal);
 } else {
 _signals[index] = newSignal;
 }
 });
 _saveToFirestore();
 }

 Future<void> _showMitigationEditor({_MitigationData? existing}) async {
 final titleController = TextEditingController(text: existing?.title ?? '');
 final descriptionController =
 TextEditingController(text: existing?.description ?? '');
 final ownerController = TextEditingController(text: existing?.owner ?? '');
 final dueController = TextEditingController(text: existing?.dueDate ?? '');
 final estimatedCostController =
 TextEditingController(text: existing?.estimatedCost ?? '');
 final statusNotesController =
 TextEditingController(text: existing?.statusNotes ?? '');
 final associatedRiskIdController =
 TextEditingController(text: existing?.associatedRiskId ?? '');
 final formKey = GlobalKey<FormState>();
 String status = existing?.status ?? 'Planning';
 int progress = existing?.progress ?? 0;

 final result = await showDialog<bool>(
 context: context,
 builder: (context) => StatefulBuilder(
 builder: (context, setDialogState) => Dialog(
 shape:
 RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
 child: ConstrainedBox(
 constraints: const BoxConstraints(maxWidth: 500),
 child: SingleChildScrollView(
 padding: const EdgeInsets.all(24),
 child: Form(
 key: formKey,
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 mainAxisSize: MainAxisSize.min,
 children: [
 Row(
 children: [
 Container(
 width: 40,
 height: 40,
 decoration: BoxDecoration(
 color: const Color(0xFFD1FAE5),
 borderRadius: BorderRadius.circular(10),
 ),
 child: const Icon(Icons.shield_rounded,
 size: 22, color: Color(0xFF10B981)),
 ),
 const SizedBox(width: 12),
 Expanded(
 child: Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Text(
 existing == null
 ? 'Add Mitigation Plan'
 : 'Edit Mitigation Plan',
 style: const TextStyle(
 fontSize: 20,
 fontWeight: FontWeight.w800,
 color: Color(0xFF111827),
 ),
 ),
 const Text('Define mitigation strategies',
 style: TextStyle(
 fontSize: 13, color: Color(0xFF6B7280))),
 ],
 ),
 ),
 IconButton(
 onPressed: () => Navigator.pop(context, false),
 icon: const Icon(Icons.close),
 ),
 ],
 ),
 const SizedBox(height: 20),
 VoiceTextFormField(
 controller: titleController,
 decoration:
 _inputDecoration('Plan Title *', Icons.shield),
 textCapitalization: TextCapitalization.sentences,
 validator: (value) =>
 value == null || value.trim().isEmpty
 ? 'Required'
 : null,
 ),
 const SizedBox(height: 14),
 VoiceTextFormField(
 controller: descriptionController,
 maxLines: 2,
 decoration: _inputDecoration(
 'Description', Icons.description_outlined),
 textCapitalization: TextCapitalization.sentences,
 ),
 const SizedBox(height: 14),
 Row(
 children: [
 Expanded(
 child: VoiceTextFormField(
 controller: ownerController,
 decoration:
 _inputDecoration('Owner', Icons.person_outline),
 textCapitalization: TextCapitalization.words,
 ),
 ),
 const SizedBox(width: 14),
 Expanded(
 child: VoiceTextFormField(
 controller: dueController,
 decoration: _inputDecoration(
 'Due Date', Icons.calendar_today),
 keyboardType: TextInputType.datetime,
 ),
 ),
 ],
 ),
 const SizedBox(height: 14),
 Row(
 children: [
 Expanded(
 child: VoiceTextFormField(
 controller: estimatedCostController,
 decoration: _inputDecoration(
 'Est. Cost (\$)', Icons.payments_outlined),
 keyboardType: TextInputType.number,
 inputFormatters: [
 FilteringTextInputFormatter.digitsOnly
 ],
 ),
 ),
 const SizedBox(width: 14),
 Expanded(
 child: DropdownButtonFormField<String>(
 value: status,
 items: const [
 'Planning',
 'In Progress',
 'Complete',
 'Blocked'
 ]
 .map((v) =>
 DropdownMenuItem(value: v, child: Text(v)))
 .toList(),
 onChanged: (v) =>
 setDialogState(() => status = v ?? status),
 decoration: _inputDecoration(
 'Status', Icons.check_circle_outline),
 ),
 ),
 ],
 ),
 const SizedBox(height: 14),
 Column(
 crossAxisAlignment: CrossAxisAlignment.start,
 children: [
 Row(
 children: [
 const Text('Progress: ',
 style: TextStyle(
 fontSize: 13, fontWeight: FontWeight.w600)),
 Text('$progress%',
 style: TextStyle(
 fontSize: 13,
 fontWeight: FontWeight.w700,
 color: _getProgressColor(progress))),
 ],
 ),
 const SizedBox(height: 8),
 Slider(
 value: progress.toDouble(),
 min: 0,
 max: 100,
 divisions: 20,
 activeColor: _getProgressColor(progress),
 onChanged: (v) =>
 setDialogState(() => progress = v.round()),
 ),
 ],
 ),
 const SizedBox(height: 14),
 VoiceTextFormField(
 controller: statusNotesController,
 maxLines: 2,
 decoration:
 _inputDecoration('Status Notes', Icons.note_outlined),
 textCapitalization: TextCapitalization.sentences,
 ),
 const SizedBox(height: 14),
 DropdownButtonFormField<String>(
 value: associatedRiskIdController.text.isEmpty
 ? null
 : associatedRiskIdController.text,
 items: _risks
 .map((r) => DropdownMenuItem(
 value: r.id,
 child: Text(r.title,
 maxLines: 1,
 overflow: TextOverflow.ellipsis),
 ))
 .toList(),
 onChanged: (v) => setDialogState(
 () => associatedRiskIdController.text = v ?? ''),
 decoration:
 _inputDecoration('Associated Risk', Icons.link),
 hint: const Text('Link to a risk'),
 ),
 const SizedBox(height: 24),
 Row(
 mainAxisAlignment: MainAxisAlignment.end,
 children: [
 TextButton(
 onPressed: () => Navigator.pop(context, false),
 style: TextButton.styleFrom(
 padding: const EdgeInsets.symmetric(
 horizontal: 24, vertical: 14),
 shape: RoundedRectangleBorder(
 borderRadius: BorderRadius.circular(10)),
 ),
 child: const Text('Cancel',
 style: TextStyle(fontWeight: FontWeight.w600)),
 ),
 const SizedBox(width: 12),
 FilledButton(
 onPressed: () {
 if (!(formKey.currentState?.validate() ?? false)) {
 return;
 }
 Navigator.pop(context, true);
 },
 style: FilledButton.styleFrom(
 backgroundColor: const Color(0xFF6366F1),
 padding: const EdgeInsets.symmetric(
 horizontal: 28, vertical: 14),
 shape: RoundedRectangleBorder(
 borderRadius: BorderRadius.circular(10)),
 ),
 child: Text(
 existing == null ? 'Add Plan' : 'Save Changes',
 style:
 const TextStyle(fontWeight: FontWeight.w600)),
 ),
 ],
 ),
 ],
 ),
 ),
 ),
 ),
 ),
 ),
 );

 titleController.dispose();
 descriptionController.dispose();
 ownerController.dispose();
 dueController.dispose();
 estimatedCostController.dispose();
 statusNotesController.dispose();
 associatedRiskIdController.dispose();

 if (result != true || !mounted) return;

 final newMitigation = _MitigationData(
 id: existing?.id ?? DateTime.now().microsecondsSinceEpoch.toString(),
 title: titleController.text.trim(),
 description: descriptionController.text.trim(),
 owner: ownerController.text.trim().isEmpty
 ? 'Unassigned'
 : ownerController.text.trim(),
 status: status,
 dueDate:
 dueController.text.trim().isEmpty ? 'TBD' : dueController.text.trim(),
 progress: progress,
 estimatedCost: estimatedCostController.text.trim(),
 statusNotes: statusNotesController.text.trim(),
 associatedRiskId: associatedRiskIdController.text.trim(),
 createdAt: existing?.createdAt ?? _formatDate(DateTime.now()),
 );

 setState(() {
 final index = _mitigations.indexWhere((m) => m.id == newMitigation.id);
 if (index == -1) {
 _mitigations.insert(0, newMitigation);
 } else {
 _mitigations[index] = newMitigation;
 }
 });
 _saveToFirestore();
 }

 InputDecoration _inputDecoration(String label, IconData icon) {
 return InputDecoration(
 labelText: label,
 prefixIcon: Icon(icon, size: 20),
 border: OutlineInputBorder(
 borderRadius: BorderRadius.circular(12),
 borderSide: const BorderSide(color: Color(0xFFD1D5DB)),
 ),
 enabledBorder: OutlineInputBorder(
 borderRadius: BorderRadius.circular(12),
 borderSide: const BorderSide(color: Color(0xFFD1D5DB)),
 ),
 focusedBorder: OutlineInputBorder(
 borderRadius: BorderRadius.circular(12),
 borderSide: const BorderSide(color: Color(0xFF6366F1), width: 2),
 ),
 contentPadding: const EdgeInsets.symmetric(horizontal: 14, vertical: 14),
 filled: true,
 fillColor: Colors.white,
 );
 }

 void _deleteRisk(String id) {
 setState(() => _risks.removeWhere((r) => r.id == id));
 _saveToFirestore();
 }

 void _deleteSignal(String id) {
 setState(() => _signals.removeWhere((s) => s.id == id));
 _saveToFirestore();
 }

 void _deleteMitigation(String id) {
 setState(() => _mitigations.removeWhere((m) => m.id == id));
 _saveToFirestore();
 }

 Future<void> _exportPdf() async {
 final projectData = ProjectDataHelper.getData(context);
 await PdfExportHelper.exportScreenPdf(
 context: context,
 screenTitle: 'Risk Tracking Workspace',
 sections: [
 PdfSection.keyValue('Project Info', [
 {'Project Name': projectData.projectName ?? 'N/A'},
 {'Solution Title': projectData.solutionTitle ?? 'N/A'},
 ]),
 PdfSection.text('Notes', projectData.planningNotes['planning_risk_tracking_workspace_notes'] ?? 'No data recorded.'),
 ],
 );
 }
}

// Data Models
class _RiskData {
 const _RiskData({
 required this.id,
 required this.title,
 this.description = '',
 this.category = 'General',
 required this.owner,
 required this.likelihoodScore,
 required this.impactScore,
 required this.probability,
 required this.impact,
 required this.riskScore,
 required this.status,
 this.triggerEvents = '',
 this.mitigationStrategy = '',
 required this.nextReview,
 this.associatedMitigation = '',
 required this.createdAt,
 required this.lastModified,
 });

 final String id;
 final String title;
 final String description;
 final String category;
 final String owner;
 final int likelihoodScore;
 final int impactScore;
 final String probability;
 final String impact;
 final int riskScore;
 final String status;
 final String triggerEvents;
 final String mitigationStrategy;
 final String nextReview;
 final String associatedMitigation;
 final String createdAt;
 final String lastModified;

 static _RiskData empty() => _RiskData(
 id: '',
 title: '',
 owner: '',
 likelihoodScore: 0,
 impactScore: 0,
 probability: '',
 impact: '',
 riskScore: 0,
 status: '',
 nextReview: '',
 createdAt: '',
 lastModified: '',
 );

 ExecutionRiskItem toShared() => ExecutionRiskItem(
 id: id,
 title: title,
 description: description,
 category: category,
 owner: owner,
 likelihoodScore: likelihoodScore,
 impactScore: impactScore,
 probability: probability,
 impact: impact,
 riskScore: riskScore,
 status: status,
 triggerEvents: triggerEvents,
 mitigationStrategy: mitigationStrategy,
 nextReview: nextReview,
 associatedMitigation: associatedMitigation,
 createdAt: createdAt,
 lastModified: lastModified,
 );

 Map<String, dynamic> toMap() => {
 'id': id,
 'title': title,
 'description': description,
 'category': category,
 'owner': owner,
 'likelihoodScore': likelihoodScore,
 'impactScore': impactScore,
 'probability': probability,
 'impact': impact,
 'riskScore': riskScore,
 'status': status,
 'triggerEvents': triggerEvents,
 'mitigationStrategy': mitigationStrategy,
 'nextReview': nextReview,
 'associatedMitigation': associatedMitigation,
 'createdAt': createdAt,
 'lastModified': lastModified,
 };

 factory _RiskData.fromMap(Map<String, dynamic> map) => _RiskData(
 id: map['id']?.toString() ?? '',
 title: map['title']?.toString() ?? '',
 description: map['description']?.toString() ?? '',
 category: map['category']?.toString() ?? 'General',
 owner: map['owner']?.toString() ?? 'Unassigned',
 likelihoodScore: map['likelihoodScore'] as int? ?? 3,
 impactScore: map['impactScore'] as int? ?? 3,
 probability: map['probability']?.toString() ?? 'Medium',
 impact: map['impact']?.toString() ?? 'Medium',
 riskScore: map['riskScore'] as int? ?? 9,
 status: map['status']?.toString() ?? 'Open',
 triggerEvents: map['triggerEvents']?.toString() ?? '',
 mitigationStrategy: map['mitigationStrategy']?.toString() ?? '',
 nextReview: map['nextReview']?.toString() ?? 'TBD',
 associatedMitigation: map['associatedMitigation']?.toString() ?? '',
 createdAt: map['createdAt']?.toString() ?? '',
 lastModified: map['lastModified']?.toString() ?? '',
 );

 factory _RiskData.fromShared(ExecutionRiskItem item) => _RiskData(
 id: item.id,
 title: item.title,
 description: item.description,
 category: item.category,
 owner: item.owner.isEmpty ? 'Unassigned' : item.owner,
 likelihoodScore: item.likelihoodScore,
 impactScore: item.impactScore,
 probability: item.probability.isEmpty ? 'Medium' : item.probability,
 impact: item.impact.isEmpty ? 'Medium' : item.impact,
 riskScore: item.riskScore,
 status: item.status.isEmpty ? 'Open' : item.status,
 triggerEvents: item.triggerEvents,
 mitigationStrategy: item.mitigationStrategy,
 nextReview: item.nextReview.isEmpty ? 'TBD' : item.nextReview,
 associatedMitigation: item.associatedMitigation,
 createdAt: item.createdAt,
 lastModified: item.lastModified,
 );
}

class _SignalData {
 const _SignalData({
 required this.id,
 required this.title,
 this.detail = '',
 required this.severity,
 this.source = '',
 required this.dateDetected,
 this.confidenceLevel = 'Medium',
 this.associatedRiskId = '',
 });

 final String id;
 final String title;
 final String detail;
 final String severity;
 final String source;
 final String dateDetected;
 final String confidenceLevel;
 final String associatedRiskId;

 ExecutionRiskSignal toShared() => ExecutionRiskSignal(
 id: id,
 title: title,
 detail: detail,
 severity: severity,
 source: source,
 dateDetected: dateDetected,
 confidenceLevel: confidenceLevel,
 associatedRiskId: associatedRiskId,
 );

 Map<String, dynamic> toMap() => {
 'id': id,
 'title': title,
 'detail': detail,
 'severity': severity,
 'source': source,
 'dateDetected': dateDetected,
 'confidenceLevel': confidenceLevel,
 'associatedRiskId': associatedRiskId,
 };

 factory _SignalData.fromMap(Map<String, dynamic> map) => _SignalData(
 id: map['id']?.toString() ?? '',
 title: map['title']?.toString() ?? '',
 detail: map['detail']?.toString() ?? '',
 severity: map['severity']?.toString() ?? 'Medium',
 source: map['source']?.toString() ?? '',
 dateDetected: map['dateDetected']?.toString() ?? '',
 confidenceLevel: map['confidenceLevel']?.toString() ?? 'Medium',
 associatedRiskId: map['associatedRiskId']?.toString() ?? '',
 );

 factory _SignalData.fromShared(ExecutionRiskSignal item) => _SignalData(
 id: item.id,
 title: item.title,
 detail: item.detail,
 severity: item.severity.isEmpty ? 'Medium' : item.severity,
 source: item.source,
 dateDetected: item.dateDetected,
 confidenceLevel:
 item.confidenceLevel.isEmpty ? 'Medium' : item.confidenceLevel,
 associatedRiskId: item.associatedRiskId,
 );
}

class _MitigationData {
 const _MitigationData({
 required this.id,
 required this.title,
 this.description = '',
 required this.owner,
 required this.status,
 required this.dueDate,
 this.progress = 0,
 this.estimatedCost = '',
 this.statusNotes = '',
 this.associatedRiskId = '',
 required this.createdAt,
 });

 final String id;
 final String title;
 final String description;
 final String owner;
 final String status;
 final String dueDate;
 final int progress;
 final String estimatedCost;
 final String statusNotes;
 final String associatedRiskId;
 final String createdAt;

 ExecutionRiskMitigation toShared({required String associatedRiskTitle}) =>
 ExecutionRiskMitigation(
 id: id,
 title: title,
 description: description,
 owner: owner,
 status: status,
 dueDate: dueDate,
 progress: progress,
 estimatedCost: estimatedCost,
 statusNotes: statusNotes,
 associatedRiskId: associatedRiskId,
 associatedRiskTitle: associatedRiskTitle,
 createdAt: createdAt,
 );

 Map<String, dynamic> toMap() => {
 'id': id,
 'title': title,
 'description': description,
 'owner': owner,
 'status': status,
 'dueDate': dueDate,
 'progress': progress,
 'estimatedCost': estimatedCost,
 'statusNotes': statusNotes,
 'associatedRiskId': associatedRiskId,
 'createdAt': createdAt,
 };

 factory _MitigationData.fromMap(Map<String, dynamic> map) => _MitigationData(
 id: map['id']?.toString() ?? '',
 title: map['title']?.toString() ?? '',
 description: map['description']?.toString() ?? '',
 owner: map['owner']?.toString() ?? 'Unassigned',
 status: map['status']?.toString() ?? 'Planning',
 dueDate: map['dueDate']?.toString() ?? 'TBD',
 progress: map['progress'] as int? ?? 0,
 estimatedCost: map['estimatedCost']?.toString() ?? '',
 statusNotes: map['statusNotes']?.toString() ?? '',
 associatedRiskId: map['associatedRiskId']?.toString() ?? '',
 createdAt: map['createdAt']?.toString() ?? '',
 );

 factory _MitigationData.fromShared(ExecutionRiskMitigation item) =>
 _MitigationData(
 id: item.id,
 title: item.title,
 description: item.description,
 owner: item.owner.isEmpty ? 'Unassigned' : item.owner,
 status: item.status.isEmpty ? 'Planning' : item.status,
 dueDate: item.dueDate.isEmpty ? 'TBD' : item.dueDate,
 progress: item.progress,
 estimatedCost: item.estimatedCost,
 statusNotes: item.statusNotes,
 associatedRiskId: item.associatedRiskId,
 createdAt: item.createdAt,
 );
}
