// Comprehensive project role catalogue.
//
// This is the single source of truth for the role titles offered by the
// Organisation Plan screens:
//
//   * Staffing Plan → "Position" picker (`_positionOptions`)
//   * Roles & Responsibilities → "Title" picker (`_roleTitleOptions`)
//
// The list is deliberately exhaustive so that any real-world project role can
// be selected without falling back to "Custom". Every title is listed exactly
// once — `test/utils/role_catalogue_test.dart` fails on duplicates.
//
// Adding a title here makes it selectable everywhere. Keep the discipline
// groupings below, and add the new category to [comprehensiveRoleTitles].

// ─── Leadership & day-to-day project management ─────────────────────────────
const List<String> leadershipAndManagementRoleTitles = <String>[
  'Project Manager',
  'Project Sponsor (Owner)',
  'Program Manager',
  'Product Owner',
  'Scrum Master',
  'Business Analyst',
  'PMO Lead',
  'PMO Manager',
  'Delivery Manager',
  'Operations Manager',
  'Risk Manager',
  'Quality Assurance Lead',
  'Quality Lead',
  'Change Manager',
  'Stakeholder Manager',
];

// ─── Executive, portfolio & business unit leadership ────────────────────────
const List<String> executiveAndPortfolioRoleTitles = <String>[
  'Chief Executive Officer',
  'Chief Operating Officer',
  'Chief Financial Officer',
  'Chief Information Officer',
  'Chief Technology Officer',
  'Chief Digital Officer',
  'Chief Data Officer',
  'Chief Information Security Officer',
  'Chief People Officer',
  'Chief Risk Officer',
  'Chief Marketing Officer',
  'Chief Transformation Officer',
  'Chief Strategy Officer',
  'Managing Director',
  'General Manager',
  'Executive Sponsor',
  'Executive Director',
  'Program Director',
  'Portfolio Manager',
  'Portfolio Analyst',
  'Portfolio Governance Lead',
  'Investment Committee Member',
  'Head of Delivery',
  'Head of Projects',
  'Head of Programmes',
  'Head of PMO',
  'Head of Engineering',
  'Head of Product',
  'Head of Operations',
  'Head of Technology',
  'Head of Transformation',
  'Head of Change',
  'Head of Quality',
  'Head of Risk',
  'Head of Digital',
  'VP of Delivery',
  'VP of Engineering',
  'VP of Product',
  'VP of Operations',
  'Director of Projects',
  'Director of Operations',
  'Director of Engineering',
  'Transformation Director',
  'Business Unit Director',
  'Regional Director',
  'Country Manager',
];

// ─── PMO, governance, controls & project support ────────────────────────────
const List<String> pmoGovernanceAndControlsRoleTitles = <String>[
  'PMO Director',
  'PMO Analyst',
  'PMO Coordinator',
  'PMO Scheduler',
  'Project Coordinator',
  'Project Controls Manager',
  'Project Controls Specialist',
  'Project Controls Analyst',
  'Project Administrator',
  'Programme Coordinator',
  'Project Support Officer',
  'Governance Analyst',
  'Governance Manager',
  'Assurance Manager',
  'Standards Manager',
  'Methodology Lead',
  'Reporting Analyst',
  'Project Reporting Lead',
  'Dashboard Analyst',
  'Resource Manager',
  'Resource Planner',
  'Resource Scheduler',
  'Demand Manager',
  'Capacity Planner',
  'Workforce Planner',
  'Document Controller',
  'Records Manager',
  'Knowledge Manager',
  'Project Auditor',
  'Interface Manager',
  'Interface',
];

// ─── Planning, scheduling & progress measurement ────────────────────────────
const List<String> planningAndSchedulingRoleTitles = <String>[
  'Planning Engineer',
  'Planning Manager',
  'Project Planning Lead',
  'Scheduler',
  'Master Scheduler',
  'Schedule Lead',
  'Schedule Analyst',
  'Senior Scheduler',
  'Cost Scheduler',
  'Critical Path Analyst',
  'Progress Measurement Analyst',
  'Earned Value Analyst',
  'Earned Value Manager',
  'Integrated Master Scheduler',
  'Baseline Controller',
  'Planning Consultant',
];

// ─── Product, requirements & business analysis ──────────────────────────────
const List<String> productAndRequirementsRoleTitles = <String>[
  'Product Manager',
  'Product Director',
  'Product Analyst',
  'Product Marketing Manager',
  'Technical Product Manager',
  'Product Operations Manager',
  'Requirements Engineer',
  'Requirements Manager',
  'Business Systems Analyst',
  'Functional Analyst',
  'Process Analyst',
  'Business Process Analyst',
  'Business Architect',
  'Product Design Lead',
  'Service Designer',
  'Domain Expert',
  'Subject Matter Expert',
  'Subject Matter Advisor',
  'Benefits Manager',
  'Benefits Realisation Lead',
  'Value Analyst',
  'Business Case Analyst',
  'Capability Manager',
  'Operating Model Designer',
];

// ─── Architecture & systems engineering ─────────────────────────────────────
const List<String> architectureAndSystemsRoleTitles = <String>[
  'Enterprise Architect',
  'Solution Architect',
  'Solutions Architect',
  'Technical Architect',
  'Software Architect',
  'Data Architect',
  'Integration Architect',
  'Security Architect',
  'Cloud Architect',
  'Infrastructure Architect',
  'Systems Architect',
  'Network Architect',
  'Platform Architect',
  'Domain Architect',
  'Lead Architect',
  'Principal Engineer',
  'Staff Engineer',
  'Distinguished Engineer',
  'Systems Engineer',
  'Systems Analyst',
  'Enterprise Engineer',
];

// ─── Software development & engineering delivery ────────────────────────────
const List<String> softwareDeliveryRoleTitles = <String>[
  'Engineering Manager',
  'Technical Manager',
  'Tech Lead',
  'Technical Lead',
  'Engineering Lead',
  'Team Lead',
  'Development Manager',
  'Software Development Manager',
  'Software Engineer',
  'Senior Software Engineer',
  'Developer',
  'Developer - Backend',
  'Developer - Frontend',
  'Developer - Fullstack',
  'Developer - Mobile',
  'Backend Engineer',
  'Frontend Engineer',
  'Full Stack Engineer',
  'Mobile Engineer',
  'iOS Engineer',
  'Android Engineer',
  'Web Developer',
  'API Engineer',
  'Integration Engineer',
  'Platform Engineer',
  'Microservices Engineer',
  'Embedded Engineer',
  'Firmware Engineer',
  'Mainframe Developer',
  'Low-Code Developer',
  'Automation Engineer',
  'Automation',
  'Configuration Engineer',
  'Build Engineer',
  'Lead Developer',
  'Front-End Lead',
  'Back-End Lead',
  'UI Engineer',
  'Release Manager',
  'Release Train Engineer',
  'Deployment Manager',
];

// ─── Data, analytics & artificial intelligence ──────────────────────────────
const List<String> dataAndAiRoleTitles = <String>[
  'Data Specialist',
  'Data Analyst',
  'Data Engineer',
  'Data Scientist',
  'Machine Learning Engineer',
  'AI Engineer',
  'AI Product Manager',
  'Prompt Engineer',
  'MLOps Engineer',
  'Analytics Engineer',
  'Business Intelligence Analyst',
  'BI Developer',
  'Reporting Engineer',
  'Data Governance Manager',
  'Data Governance Officer',
  'Data Quality Analyst',
  'Data Steward',
  'Master Data Manager',
  'Database Administrator',
  'ETL Developer',
  'Data Warehouse Engineer',
  'Statistician',
  'Operations Research Analyst',
  'Visualisation Specialist',
  'Data Privacy Officer',
  'Customer Insight Analyst',
];

// ─── Cloud, infrastructure, networking & DevOps ─────────────────────────────
const List<String> cloudInfrastructureAndDevOpsRoleTitles = <String>[
  'DevOps Engineer',
  'DevOps Manager',
  'Site Reliability Engineer',
  'Platform Reliability Engineer',
  'Cloud Engineer',
  'Cloud Administrator',
  'Cloud Solutions Consultant',
  'Systems Administrator',
  'Network Engineer',
  'Network Administrator',
  'Infrastructure Engineer',
  'Infrastructure Manager',
  'Infrastructure Analyst',
  'Virtualisation Engineer',
  'Storage Engineer',
  'Backup and Recovery Engineer',
  'Telecommunications Engineer',
  'Voice and Data Engineer',
  'NOC Engineer',
  'Data Centre Manager',
  'End User Computing Engineer',
  'IT Support Engineer',
  'IT Support Analyst',
  'Service Desk Analyst',
  'Desktop Support Technician',
  'Systems Integrator',
  'Middleware Engineer',
];

// ─── Security, privacy & compliance ─────────────────────────────────────────
const List<String> securityAndComplianceRoleTitles = <String>[
  'Cyber Security Analyst',
  'Cyber Security Engineer',
  'Information Security Manager',
  'Security Operations Centre Analyst',
  'Penetration Tester',
  'Ethical Hacker',
  'Application Security Engineer',
  'Network Security Engineer',
  'Identity and Access Management Analyst',
  'GRC Analyst',
  'Compliance Officer',
  'Compliance Manager',
  'Compliance Analyst',
  'Data Protection Officer',
  'Privacy Officer',
  'Records and Information Manager',
  'Security Consultant',
  'Threat Intelligence Analyst',
  'Incident Response Analyst',
  'Vulnerability Analyst',
  'Security Awareness Lead',
];

// ─── Quality assurance, testing & continuous improvement ────────────────────
const List<String> qualityAndTestingRoleTitles = <String>[
  'Test Lead',
  'Test Manager',
  'QA Lead',
  'QA Engineer',
  'QA Analyst',
  'Quality Assurance Manager',
  'Quality Assurance Analyst',
  'Quality Manager',
  'Quality Engineer',
  'Quality Control Inspector',
  'Quality Control Analyst',
  'Quality Control',
  'Quality Systems Manager',
  'Quality Auditor',
  'Test Analyst',
  'Tester',
  'Test Automation Engineer',
  'Performance Test Engineer',
  'Manual Tester',
  'Software Tester',
  'User Acceptance Test Coordinator',
  'Verification and Validation Engineer',
  'Regulatory Affairs Specialist',
  'Continuous Improvement Manager',
  'Six Sigma Black Belt',
  'Process Improvement Analyst',
];

// ─── Risk, audit, assurance & business continuity ───────────────────────────
const List<String> riskAndAuditRoleTitles = <String>[
  'Risk Analyst',
  'Risk Officer',
  'Risk and Compliance Manager',
  'Enterprise Risk Manager',
  'Operational Risk Analyst',
  'Project Risk Analyst',
  'Risk Consultant',
  'Internal Auditor',
  'Audit Manager',
  'External Auditor',
  'Assurance Analyst',
  'Controls Analyst',
  'Fraud Analyst',
  'Business Continuity Manager',
  'Crisis Management Lead',
  'Insurance and Claims Specialist',
  'Contract Auditor',
];

// ─── Procurement, contracts & commercial ────────────────────────────────────
const List<String> procurementAndCommercialRoleTitles = <String>[
  'Procurement Manager',
  'Procurement Lead',
  'Procurement Officer',
  'Procurement',
  'Procurement Specialist',
  'Sourcing Manager',
  'Category Manager',
  'Strategic Sourcing Analyst',
  'Vendor Manager',
  'Vendor Relationship Manager',
  'Supplier Manager',
  'Contracts Manager',
  'Contracts Lead',
  'Contracts Administrator',
  'Contract Specialist',
  'Commercial Manager',
  'Commercial Director',
  'Commercial Analyst',
  'Bid Manager',
  'Bid Writer',
  'Tender Manager',
  'Bid and Proposal Manager',
  'Cost and Commercial Lead',
  'Pricing Analyst',
  'Claims Manager',
];

// ─── Finance, cost engineering & budget control ─────────────────────────────
const List<String> financeAndCostRoleTitles = <String>[
  'Cost Lead',
  'Cost Estimator',
  'Cost Engineer',
  'Cost Controller',
  'Cost Analyst',
  'Cost Consultant',
  'Quantity Surveyor',
  'Senior Quantity Surveyor',
  'Quantity Surveyor Lead',
  'Financial Controller',
  'Finance Manager',
  'Finance Business Partner',
  'Financial Analyst',
  'Budget Analyst',
  'Treasury Analyst',
  'Project Accountant',
  'Management Accountant',
  'Accounts Payable Officer',
  'Accounts Receivable Officer',
  'Payroll Officer',
  'Tax Specialist',
  'Billing Analyst',
  'Investment Analyst',
  'Invoice Controller',
  'Capital Planning Analyst',
];

// ─── Engineering disciplines, construction & asset management ───────────────
const List<String> engineeringAndConstructionRoleTitles = <String>[
  'Project Engineer',
  'Engineer',
  'Design Engineer',
  'Civil Engineer',
  'Structural Engineer',
  'Mechanical Engineer',
  'Electrical Engineer',
  'Electronics Engineer',
  'Process Engineer',
  'Chemical Engineer',
  'Mining Engineer',
  'Geotechnical Engineer',
  'Geological Engineer',
  'Environmental Engineer',
  'Water Engineer',
  'Sanitary Engineer',
  'Highways Engineer',
  'Rail Engineer',
  'Bridge Engineer',
  'Building Services Engineer',
  'HVAC Engineer',
  'Piping Engineer',
  'Instrumentation and Control Engineer',
  'Commissioning Engineer',
  'Construction Manager',
  'Construction Supervisor',
  'Site Manager',
  'Site Engineer',
  'Site Supervisor',
  'Foreman',
  'General Foreman',
  'Project Superintendent',
  'Resident Engineer',
  'Clerk of Works',
  'Surveyor',
  'Land Surveyor',
  'Architect',
  'Landscape Architect',
  'Urban Planner',
  'Interior Designer',
  'Building Information Modelling Coordinator',
  'BIM Manager',
  'BIM Specialist',
  'Draughtsperson',
  'Technical Draughtsperson',
  'Fabricator',
  'Welder',
  'Electrician',
  'Plumber',
  'Carpenter',
  'Rigger',
  'Scaffolder',
  'Plant Operator',
  'Machinery Operator',
  'Toolroom Technician',
  'Maintenance Engineer',
  'Mechanical Technician',
  'Electrical Technician',
  'Instrumentation Technician',
  'Facilities Engineer',
  'Facilities Manager',
  'Asset Manager',
  'Reliability Engineer',
  'Planned Maintenance Coordinator',
  'Startup Manager',
];

// ─── Design, research & creative ────────────────────────────────────────────
const List<String> designAndCreativeRoleTitles = <String>[
  'Lead Designer',
  'Design Lead',
  'Designer - UX',
  'Designer - UI',
  'UX Researcher',
  'UX Designer',
  'UI Designer',
  'Interaction Designer',
  'Visual Designer',
  'Product Designer',
  'Graphic Designer',
  'Brand Designer',
  'Motion Designer',
  'Illustrator',
  'Content Designer',
  'Design Systems Lead',
  'Creative Director',
  'Art Director',
  'Copywriter',
  'Technical Writer',
  'Documentation Specialist',
  'Accessibility Specialist',
  'Instructional Designer',
  'Research and Development Manager',
  'Research Scientist',
  'Ergonomist',
  'Human Factors Specialist',
];

// ─── Agile, lean & delivery leadership ──────────────────────────────────────
const List<String> agileAndDeliveryRoleTitles = <String>[
  'Agile Coach',
  'Agile Delivery Lead',
  'Agile Project Manager',
  'Agile Programme Manager',
  'Kanban Coach',
  'DevOps Coach',
  'Delivery Lead',
  'Delivery Director',
  'Iteration Manager',
  'Sprint Lead',
  'Backlog Manager',
  'Value Stream Manager',
  'Lean Portfolio Manager',
  'Workstream Lead',
  'Stream Lead',
];

// ─── Operations, service management & support ───────────────────────────────
const List<String> operationsAndServiceRoleTitles = <String>[
  'Business Manager',
  'Operations Lead',
  'Operations Analyst',
  'Operations Liaison',
  'Service Delivery Manager',
  'Service Manager',
  'IT Service Manager',
  'Incident Manager',
  'Problem Manager',
  'Change and Release Coordinator',
  'Service Transition Manager',
  'Service Level Manager',
  'Business Operations Manager',
  'Production Manager',
  'Production Planner',
  'Manufacturing Manager',
  'Logistics Manager',
  'Supply Chain Manager',
  'Warehouse Manager',
  'Inventory Controller',
  'Distribution Manager',
  'Fleet Manager',
  'Maintenance Planner',
  'Hypercare',
  'Hypercare Lead',
  'Production Support Analyst',
  'Application Support Analyst',
  'Support Team Lead',
  'Customer Support Manager',
  'Technical Support Engineer',
];

// ─── Change, training, capability & communications ──────────────────────────
const List<String> changeAndCommunicationsRoleTitles = <String>[
  'Change Lead',
  'Change Analyst',
  'Change Champion',
  'Organizational Change Manager',
  'Business Readiness Lead',
  'Adoption Lead',
  'User Adoption Specialist',
  'Training Manager',
  'Training Lead',
  'Training Coordinator',
  'Learning and Development Manager',
  'Learning Partner',
  'Capability Development Lead',
  'Technical Trainer',
  'Communications Manager',
  'Communications Lead',
  'Communications Officer',
  'Internal Communications Specialist',
  'PR and Media Officer',
  'Engagement Manager',
  'Community Engagement Officer',
  'Knowledge Transfer Lead',
];

// ─── Stakeholders, customers, marketing & partnerships ──────────────────────
const List<String> stakeholderAndCustomerRoleTitles = <String>[
  'Stakeholder Engagement Lead',
  'Stakeholder Analyst',
  'Customer Relationship Manager',
  'Account Manager',
  'Key Account Manager',
  'Client Partner',
  'Business Development Manager',
  'Sales Director',
  'Sales Manager',
  'Customer Success Manager',
  'Customer Experience Manager',
  'Marketing Manager',
  'Digital Marketing Specialist',
  'Product Marketing Lead',
  'Market Research Analyst',
  'Brand Manager',
  'Growth Manager',
  'Partnership Manager',
  'Channel Manager',
  'Public Relations Manager',
  'Corporate Affairs Manager',
  'External Affairs Lead',
];

// ─── People, HR, workforce & administration ─────────────────────────────────
const List<String> peopleAndWorkforceRoleTitles = <String>[
  'HR Manager',
  'HR Business Partner',
  'HR Analyst',
  'People Partner',
  'Recruitment Manager',
  'Talent Acquisition Specialist',
  'Talent Manager',
  'Resourcing Manager',
  'Workforce Manager',
  'Employee Relations Specialist',
  'Compensation and Benefits Analyst',
  'Organisational Development Manager',
  'Diversity and Inclusion Lead',
  'Performance and Reward Manager',
  'Team Administrator',
  'Office Manager',
  'Administration Manager',
  'Executive Assistant',
  'Personal Assistant',
  'Receptionist',
];

// ─── Health, safety, environment, security & sustainability ─────────────────
const List<String> hseAndSustainabilityRoleTitles = <String>[
  'SSHER Lead',
  'Health and Safety Manager',
  'Health and Safety Officer',
  'Safety Officer',
  'SHEQ Manager',
  'Environmental Manager',
  'Environmental Officer',
  'Environmental Health Officer',
  'Sustainability Manager',
  'Sustainability Analyst',
  'Climate Risk Analyst',
  'Waste Management Officer',
  'Security Manager',
  'Security Officer',
  'Physical Security Lead',
  'Emergency Response Coordinator',
  'First Aid Officer',
  'Community Liaison Officer',
  'Social Performance Manager',
];

// ─── Legal, regulatory & corporate governance ───────────────────────────────
const List<String> legalAndRegulatoryRoleTitles = <String>[
  'Legal Counsel',
  'Senior Legal Counsel',
  'General Counsel',
  'Legal Advisor',
  'Contracts Counsel',
  'Litigation Manager',
  'Regulatory Affairs Manager',
  'Regulatory Compliance Analyst',
  'Company Secretary',
  'Board Secretary',
  'Corporate Governance Officer',
  'Intellectual Property Advisor',
  'Policy Advisor',
  'Policy Analyst',
  'Permitting Specialist',
  'Licensing Officer',
  'Statutory Approvals Lead',
  'Ethics and Integrity Officer',
];

// ─── Consulting, technology & specialist capability ─────────────────────────
const List<String> consultingAndSpecialistRoleTitles = <String>[
  'Solutions Consultant',
  'Pre-Sales Consultant',
  'Technical Consultant',
  'Technology Consultant',
  'Management Consultant',
  'Business Consultant',
  'Strategy Consultant',
  'Change and Transformation Consultant',
  'Digital Transformation Lead',
  'Innovation Manager',
  'Systems Consultant',
  'Testing Consultant',
  'Product Research Analyst',
  'Robotics Engineer',
  'Automation Specialist',
  'IoT Engineer',
  'Blockchain Developer',
  'AR/VR Developer',
  'Game Developer',
  'Quantum Computing Researcher',
  'Green Technology Specialist',
  'Digital Twin Specialist',
  'Drone Operator',
  'GIS Analyst',
  'Geospatial Analyst',
  'Simulation Engineer',
  'Metrology Specialist',
  'Laboratory Technician',
  'Field Technician',
  'Commissioning Technician',
  'Testing Technician',
  'Calibration Technician',
  'Technical Assessor',
  'Independent Verifier',
  'Peer Reviewer',
];

/// Every role title known to the app, grouped by discipline in the order the
/// pickers should present them.
///
/// Leadership and day-to-day project roles come first because they are the
/// most frequently selected; the remainder follow by discipline.
const List<String> comprehensiveRoleTitles = <String>[
  ...leadershipAndManagementRoleTitles,
  ...executiveAndPortfolioRoleTitles,
  ...pmoGovernanceAndControlsRoleTitles,
  ...planningAndSchedulingRoleTitles,
  ...productAndRequirementsRoleTitles,
  ...architectureAndSystemsRoleTitles,
  ...softwareDeliveryRoleTitles,
  ...dataAndAiRoleTitles,
  ...cloudInfrastructureAndDevOpsRoleTitles,
  ...securityAndComplianceRoleTitles,
  ...qualityAndTestingRoleTitles,
  ...riskAndAuditRoleTitles,
  ...procurementAndCommercialRoleTitles,
  ...financeAndCostRoleTitles,
  ...engineeringAndConstructionRoleTitles,
  ...designAndCreativeRoleTitles,
  ...agileAndDeliveryRoleTitles,
  ...operationsAndServiceRoleTitles,
  ...changeAndCommunicationsRoleTitles,
  ...stakeholderAndCustomerRoleTitles,
  ...peopleAndWorkforceRoleTitles,
  ...hseAndSustainabilityRoleTitles,
  ...legalAndRegulatoryRoleTitles,
  ...consultingAndSpecialistRoleTitles,
];

/// A discipline heading plus the role titles listed beneath it.
class RoleDisciplineGroup {
  const RoleDisciplineGroup(this.label, this.titles);

  final String label;
  final List<String> titles;
}

/// Splits [titles] into discipline groups in catalogue display order.
///
/// Titles that are not in the catalogue (for example a trailing 'Custom'
/// option) are collected into a final "Other" group, so callers can pass a
/// picker's full option list without pre-sorting it.
List<RoleDisciplineGroup> groupRolesByDiscipline(Iterable<String> titles) {
  final remaining = titles.toSet();
  final groups = <RoleDisciplineGroup>[];

  for (final entry in roleTitlesByDiscipline.entries) {
    final matched =
        entry.value.where(remaining.contains).toList(growable: false);
    if (matched.isEmpty) continue;
    groups.add(RoleDisciplineGroup(entry.key, matched));
    remaining.removeAll(matched);
  }

  if (remaining.isNotEmpty) {
    groups.add(RoleDisciplineGroup('Other', remaining.toList(growable: false)));
  }

  return groups;
}

/// Role titles keyed by the discipline heading shown in the pickers.
const Map<String, List<String>> roleTitlesByDiscipline = <String, List<String>>{
  'Leadership & Project Management': leadershipAndManagementRoleTitles,
  'Executive & Portfolio': executiveAndPortfolioRoleTitles,
  'PMO, Governance & Controls': pmoGovernanceAndControlsRoleTitles,
  'Planning & Scheduling': planningAndSchedulingRoleTitles,
  'Product & Requirements': productAndRequirementsRoleTitles,
  'Architecture & Systems': architectureAndSystemsRoleTitles,
  'Software Delivery': softwareDeliveryRoleTitles,
  'Data & AI': dataAndAiRoleTitles,
  'Cloud & Infrastructure': cloudInfrastructureAndDevOpsRoleTitles,
  'Security & Compliance': securityAndComplianceRoleTitles,
  'Quality & Testing': qualityAndTestingRoleTitles,
  'Risk & Audit': riskAndAuditRoleTitles,
  'Procurement & Commercial': procurementAndCommercialRoleTitles,
  'Finance & Cost': financeAndCostRoleTitles,
  'Engineering & Construction': engineeringAndConstructionRoleTitles,
  'Design & Creative': designAndCreativeRoleTitles,
  'Agile & Delivery': agileAndDeliveryRoleTitles,
  'Operations & Service': operationsAndServiceRoleTitles,
  'Change & Communications': changeAndCommunicationsRoleTitles,
  'Stakeholders & Customers': stakeholderAndCustomerRoleTitles,
  'People & Workforce': peopleAndWorkforceRoleTitles,
  'HSE & Sustainability': hseAndSustainabilityRoleTitles,
  'Legal & Regulatory': legalAndRegulatoryRoleTitles,
  'Consulting & Specialists': consultingAndSpecialistRoleTitles,
};
