library;

/// World countries and currencies data for onboarding and app-wide use.
///
/// The country list includes all 195 UN-recognized countries plus commonly
/// used territories. The currency list includes all ISO 4217 currencies.
///
/// The onboarding flow uses these lists so users can select from the
/// complete set of countries and currencies worldwide. The selections are
/// stored via [UserPreferencesService] and read across the app for
/// currency formatting, date formats, and regional compliance hints.

/// All world countries (alphabetical), ending with 'Other'.
const List<String> worldCountries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua and Barbuda',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cabo Verde',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Palestine',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe',
  'Other',
];

/// All ISO 4217 world currencies (alphabetical by code), ending with 'Other'.
/// Format: 'CODE (symbol) — Currency Name'
const List<String> worldCurrencies = [
  'AFN (؋) — Afghan Afghani',
  'ALL (L) — Albanian Lek',
  'AMD (֏) — Armenian Dram',
  'ANG (ƒ) — Netherlands Antillean Guilder',
  'AOA (Kz) — Angolan Kwanza',
  'ARS (A\$) — Argentine Peso',
  'AUD (A\$) — Australian Dollar',
  'AWG (ƒ) — Aruban Florin',
  'AZN (₼) — Azerbaijani Manat',
  'BAM (KM) — Bosnia-Herzegovina Convertible Mark',
  'BBD (Bds\$) — Barbadian Dollar',
  'BDT (৳) — Bangladeshi Taka',
  'BGN (лв) — Bulgarian Lev',
  'BHD (.د.ب) — Bahraini Dinar',
  'BIF (FBu) — Burundian Franc',
  'BMD (BD\$) — Bermudian Dollar',
  'BND (B\$) — Brunei Dollar',
  'BOB (Bs) — Bolivian Boliviano',
  'BRL (R\$) — Brazilian Real',
  'BSD (B\$) — Bahamian Dollar',
  'BTN (Nu) — Bhutanese Ngultrum',
  'BWP (P) — Botswanan Pula',
  'BYN (Br) — Belarusian Ruble',
  'BZD (BZ\$) — Belize Dollar',
  'CAD (C\$) — Canadian Dollar',
  'CDF (FC) — Congolese Franc',
  'CHF (CHF) — Swiss Franc',
  'CLP (CL\$) — Chilean Peso',
  'CNY (¥) — Chinese Yuan',
  'COP (CO\$) — Colombian Peso',
  'CRC (₡) — Costa Rican Colón',
  'CUP (₱) — Cuban Peso',
  'CZK (Kč) — Czech Koruna',
  'DJF (Fdj) — Djiboutian Franc',
  'DKK (kr) — Danish Krone',
  'DOP (RD\$) — Dominican Peso',
  'DZD (دج) — Algerian Dinar',
  'EGP (E£) — Egyptian Pound',
  'ERN (Nfk) — Eritrean Nakfa',
  'ETB (Br) — Ethiopian Birr',
  'EUR (€) — Euro',
  'FJD (FJ\$) — Fijian Dollar',
  'GBP (£) — British Pound',
  'GEL (₾) — Georgian Lari',
  'GHS (₵) — Ghanaian Cedi',
  'GIP (£) — Gibraltar Pound',
  'GMD (D) — Gambian Dalasi',
  'GNF (FG) — Guinean Franc',
  'GTQ (Q) — Guatemalan Quetzal',
  'GYD (G\$) — Guyanese Dollar',
  'HKD (HK\$) — Hong Kong Dollar',
  'HNL (L) — Honduran Lempira',
  'HRK (kn) — Croatian Kuna',
  'HTG (G) — Haitian Gourde',
  'HUF (Ft) — Hungarian Forint',
  'IDR (Rp) — Indonesian Rupiah',
  'ILS (₪) — Israeli Shekel',
  'INR (₹) — Indian Rupee',
  'IQD (ع.د) — Iraqi Dinar',
  'IRR (﷼) — Iranian Rial',
  'ISK (kr) — Icelandic Króna',
  'JMD (J\$) — Jamaican Dollar',
  'JOD (JD) — Jordanian Dinar',
  'JPY (¥) — Japanese Yen',
  'KES (KSh) — Kenyan Shilling',
  'KGS (с) — Kyrgystani Som',
  'KHR (៛) — Cambodian Riel',
  'KMF (CF) — Comorian Franc',
  'KPW (₩) — North Korean Won',
  'KRW (₩) — South Korean Won',
  'KWD (KD) — Kuwaiti Dinar',
  'KYD (KY\$) — Cayman Islands Dollar',
  'KZT (₸) — Kazakhstani Tenge',
  'LAK (₭) — Laotian Kip',
  'LBP (ل.ل) — Lebanese Pound',
  'LKR (Rs) — Sri Lankan Rupee',
  'LRD (L\$) — Liberian Dollar',
  'LSL (L) — Lesotho Loti',
  'LYD (LD) — Libyan Dinar',
  'MAD (د.م.) — Moroccan Dirham',
  'MDL (L) — Moldovan Leu',
  'MGA (Ar) — Malagasy Ariary',
  'MKD (ден) — Macedonian Denar',
  'MMK (K) — Burmese Kyat',
  'MNT (₮) — Mongolian Tugrik',
  'MOP (MOP\$) — Macanese Pataca',
  'MRU (UM) — Mauritanian Ouguiya',
  'MUR (Rs) — Mauritian Rupee',
  'MVR (Rf) — Maldivian Rufiyaa',
  'MWK (MK) — Malawian Kwacha',
  'MXN (MX\$) — Mexican Peso',
  'MYR (RM) — Malaysian Ringgit',
  'MZN (MT) — Mozambican Metical',
  'NAD (N\$) — Namibian Dollar',
  'NGN (₦) — Nigerian Naira',
  'NIO (C\$) — Nicaraguan Córdoba',
  'NOK (kr) — Norwegian Krone',
  'NPR (Rs) — Nepalese Rupee',
  'NZD (NZ\$) — New Zealand Dollar',
  'OMR (﷼) — Omani Rial',
  'PAB (B/.) — Panamanian Balboa',
  'PEN (S/) — Peruvian Sol',
  'PGK (K) — Papua New Guinean Kina',
  'PHP (₱) — Philippine Peso',
  'PKR (Rs) — Pakistani Rupee',
  'PLN (zł) — Polish Zloty',
  'PYG (₲) — Paraguayan Guaraní',
  'QAR (﷼) — Qatari Riyal',
  'RON (lei) — Romanian Leu',
  'RSD (дин) — Serbian Dinar',
  'RUB (₽) — Russian Ruble',
  'RWF (FRw) — Rwandan Franc',
  'SAR (﷼) — Saudi Riyal',
  'SBD (SI\$) — Solomon Islands Dollar',
  'SCR (Rs) — Seychellois Rupee',
  'SDG (£) — Sudanese Pound',
  'SEK (kr) — Swedish Krona',
  'SGD (S\$) — Singapore Dollar',
  'SLL (Le) — Sierra Leonean Leone',
  'SOS (Sh) — Somali Shilling',
  'SRD (Sr\$) — Surinamese Dollar',
  'SSP (£) — South Sudanese Pound',
  'STN (Db) — São Tomé and Príncipe Dobra',
  'SYP (£) — Syrian Pound',
  'SZL (E) — Swazi Lilangeni',
  'THB (฿) — Thai Baht',
  'TJS (ЅМ) — Tajikistani Somoni',
  'TMT (m) — Turkmenistani Manat',
  'TND (د.ت) — Tunisian Dinar',
  'TOP (T\$) — Tongan Paʻanga',
  'TRY (₺) — Turkish Lira',
  'TTD (TT\$) — Trinidad and Tobago Dollar',
  'TWD (NT\$) — Taiwan Dollar',
  'TZS (TSh) — Tanzanian Shilling',
  'UAH (₴) — Ukrainian Hryvnia',
  'UGX (USh) — Ugandan Shilling',
  'USD (\$) — US Dollar',
  'UYU (\$U) — Uruguayan Peso',
  'UZS (soʻm) — Uzbekistani Som',
  'VES (Bs) — Venezuelan Bolívar',
  'VND (₫) — Vietnamese Dong',
  'VUV (Vt) — Vanuatu Vatu',
  'WST (WS\$) — Samoan Tala',
  'XAF (FCFA) — Central African CFA Franc',
  'XCD (EC\$) — East Caribbean Dollar',
  'XOF (CFA) — West African CFA Franc',
  'XPF (CFP) — CFP Franc',
  'YER (﷼) — Yemeni Rial',
  'ZAR (R) — South African Rand',
  'ZMW (ZK) — Zambian Kwacha',
  'ZWL (Z\$) — Zimbabwean Dollar',
  'Other',
];

/// Extract the ISO 4217 currency code from a currency string like
/// 'USD (\$) — US Dollar' → 'USD'.
String extractCurrencyCode(String currencyString) {
  if (currencyString == 'Other') return 'USD';
  final spaceIndex = currencyString.indexOf(' ');
  if (spaceIndex > 0) return currencyString.substring(0, spaceIndex);
  return 'USD';
}

/// Extract the currency symbol from a currency string like
/// 'USD (\$) — US Dollar' → '\$'.
String extractCurrencySymbol(String currencyString) {
  if (currencyString == 'Other') return '\$';
  final start = currencyString.indexOf('(');
  final end = currencyString.indexOf(')');
  if (start >= 0 && end > start) {
    return currencyString.substring(start + 1, end);
  }
  return '\$';
}

/// Extract the currency name from a currency string like
/// 'USD (\$) — US Dollar' → 'US Dollar'.
String extractCurrencyName(String currencyString) {
  if (currencyString == 'Other') return 'US Dollar';
  final dashIndex = currencyString.indexOf('—');
  if (dashIndex >= 0) {
    return currencyString.substring(dashIndex + 1).trim();
  }
  return currencyString;
}
